import { StyleSheet } from 'react-native';
import { typography } from '../../app/theme/tokens/typography';

export const DETAIL_DIVIDER_COLOR = '#00000008';
// Community comment separators use a neutral, low-contrast black so their
// structure remains legible without changing the shared detail separators.
export const COMMENT_ROOT_DIVIDER_COLOR = 'rgba(0, 0, 0, 0.08)';
export const COMMENT_REPLY_DIVIDER_COLOR = 'rgba(0, 0, 0, 0.04)';
export const COMMENT_REPLY_DIVIDER_WIDTH = 1;
export const COMMENT_BUBBLE_SURFACES = {
  light: '#F4F4F5',
  dark: '#27272A',
} as const;

const DISCUSSION_BODY_TYPOGRAPHY = {
  ...typography.role.body,
  lineHeight: 25,
};

export const styles = StyleSheet.create({
  bodyButton: {
    minHeight: 48,
    paddingHorizontal: 4,
    justifyContent: 'center',
    alignItems: 'center',
  },
  readRetry: {
    minHeight: 48,
    paddingHorizontal: 20,
    paddingVertical: 8,
    justifyContent: 'center',
    gap: 4,
  },
  screen: {
    flex: 1,
  },
  contentArea: {
    flex: 1,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingBottom: 12,
  },
  headerSide: {
    width: 44,
    alignItems: 'flex-start',
    justifyContent: 'center',
  },
  backButton: {
    width: 44,
    height: 44,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: {
    flex: 1,
    textAlign: 'center',
  },
  centerState: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 28,
  },
  stateTitle: {
    marginBottom: 8,
    textAlign: 'center',
  },
  stateBody: {
    textAlign: 'center',
    lineHeight: 22,
  },
  stateButton: {
    marginTop: 18,
    minHeight: 44,
    borderRadius: 999,
    paddingHorizontal: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  stateButtonText: {
    color: '#FFFFFF',
    fontWeight: '700',
  },
  scrollContent: {
    paddingHorizontal: 20,
    gap: 12,
    paddingTop: 12,
  },
  postSection: {
    paddingTop: 4,
    paddingBottom: 18,
    gap: 16,
  },
  postCard: {
    borderWidth: 1,
    borderRadius: 22,
    padding: 18,
    gap: 16,
  },
  postTitleRow: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    gap: 8,
  },
  authorBlock: {
    flex: 1,
    gap: 4,
  },
  postMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    flexWrap: 'wrap',
    gap: 8,
  },
  authorName: {
    ...DISCUSSION_BODY_TYPOGRAPHY,
    fontWeight: '700',
  },
  petNameLine: {
    ...typography.role.body,
    fontWeight: '600',
  },
  metaLine: {
    ...typography.role.helper,
  },
  categoryBadge: {
    minHeight: 20,
    borderRadius: 6,
    paddingHorizontal: 6,
    paddingVertical: 2,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    flexShrink: 0,
  },
  categoryText: {
    ...typography.role.helper,
    fontSize: 11,
    lineHeight: 16,
    fontWeight: '600',
  },
  moreButton: {
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
  },
  postTitle: {
    ...typography.role.titleLg,
    alignSelf: 'stretch',
    flexShrink: 1,
    minWidth: 0,
    fontSize: 20,
    lineHeight: 28,
    fontWeight: '700',
  },
  mediaSection: {
    marginTop: 4,
    marginBottom: 6,
  },
  postContent: {
    ...DISCUSSION_BODY_TYPOGRAPHY,
  },
  postContentSection: {
    borderTopWidth: 1,
    paddingTop: 12,
    paddingBottom: 8,
  },
  postImage: {
    width: '100%',
    height: 260,
    borderRadius: 18,
  },
  imageFallback: {
    minHeight: 84,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  imageFallbackText: {
    ...typography.role.helper,
  },
  actionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    paddingTop: 2,
    justifyContent: 'space-between',
  },
  actionPill: {
    minHeight: 44,
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  actionPillText: {
    ...typography.role.helper,
    fontWeight: '700',
  },
  countRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
  },
  countItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  countText: {
    ...typography.role.helper,
  },
  commentsCard: {
    borderWidth: 1,
    borderRadius: 22,
    padding: 18,
  },
  commentsSection: {
    paddingTop: 6,
  },
  commentsHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingBottom: 10,
    borderTopWidth: 1,
    borderTopColor: DETAIL_DIVIDER_COLOR,
    marginBottom: 8,
  },
  commentsSortHeader: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
    minHeight: 48,
    paddingBottom: 2,
  },
  commentsTitle: {
    ...typography.role.bodySm,
    fontWeight: '600',
    includeFontPadding: false,
    textAlignVertical: 'center',
    flexShrink: 1,
  },
  commentsTitleRow: {
    minHeight: 48,
    flex: 1,
    minWidth: 0,
    marginRight: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  commentsCount: {
    ...typography.role.bodySm,
    fontWeight: '600',
    includeFontPadding: false,
    textAlignVertical: 'center',
  },
  commentSortLabel: {
    minHeight: 48,
    paddingHorizontal: 4,
    paddingVertical: 0,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
  },
  commentSortText: {
    ...typography.role.caption,
    lineHeight: typography.role.titleSm.lineHeight,
    includeFontPadding: false,
    textAlignVertical: 'center',
  },
  commentSortOptions: {
    gap: 8,
  },
  commentSortOption: {
    minHeight: 60,
    borderRadius: 14,
    borderWidth: 1,
    paddingHorizontal: 14,
    paddingVertical: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  commentSortOptionCopy: {
    flex: 1,
    gap: 2,
  },
  commentsLoading: {
    paddingVertical: 10,
  },
  emptyComments: {
    ...typography.role.bodySm,
  },
  commentItemWrap: {
    paddingHorizontal: 20,
    paddingVertical: 14,
  },
  commentThreadWrap: {
    // Root content and replies have different horizontal-boundary contracts:
    // roots own their inner padding while the reply section can reach the
    // comment viewport edge without a compensating margin patch.
    paddingHorizontal: 0,
    paddingVertical: 0,
    marginBottom: 8,
    borderBottomWidth: 0,
    borderBottomColor: DETAIL_DIVIDER_COLOR,
    borderRadius: 0,
  },
  commentRootContent: {
    paddingHorizontal: 20,
    paddingTop: 6,
    paddingBottom: 2,
  },
  commentRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
  },
  commentAvatarTapTarget: {
    alignSelf: 'flex-start',
  },
  commentTapContent: {
    minHeight: 48,
    alignSelf: 'stretch',
    minWidth: 0,
  },
  commentTapPressed: {
    opacity: 0.76,
  },
  commentAvatar: {
    width: 28,
    height: 28,
    borderRadius: 14,
    borderWidth: 1,
    marginTop: 0,
  },
  commentAvatarFallback: {
    width: 28,
    height: 28,
    borderRadius: 14,
    borderWidth: 1,
    marginTop: 0,
    alignItems: 'center',
    justifyContent: 'center',
  },
  commentBodyWrap: {
    flex: 1,
    minWidth: 0,
  },
  commentMetaRow: {
    marginBottom: 4,
  },
  commentMetaInline: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 6,
  },
  commentMetaText: {
    ...typography.role.helper,
  },
  commentAuthorText: {
    maxWidth: '100%',
    flexShrink: 1,
    ...DISCUSSION_BODY_TYPOGRAPHY,
    fontWeight: '700',
  },
  authorBadge: {
    minHeight: 18,
    borderWidth: 1,
    borderRadius: 5,
    paddingHorizontal: 6,
    alignItems: 'center',
    justifyContent: 'center',
  },
  authorBadgeText: {
    ...typography.role.caption,
    fontWeight: '800',
  },
  bestBadge: {
    minHeight: 18,
    borderRadius: 9,
    paddingHorizontal: 6,
    alignItems: 'center',
    justifyContent: 'center',
  },
  bestBadgeText: {
    ...typography.role.caption,
    fontWeight: '700',
  },
  commentBubble: {
    borderRadius: 8,
    borderWidth: 0,
    paddingHorizontal: 10,
    paddingVertical: 6,
    alignSelf: 'flex-start',
    maxWidth: '100%',
  },
  commentActionRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: 4,
    marginTop: 0,
    paddingLeft: 0,
  },
  commentActionText: {
    ...typography.role.helper,
    fontSize: 12,
    fontWeight: '500',
  },
  commentLikeGroup: {
    flexDirection: 'row',
    gap: 4,
  },
  commentActionTouchTarget: {
    minHeight: 48,
    minWidth: 48,
    alignItems: 'center',
    justifyContent: 'center',
  },
  commentActionFace: {
    paddingHorizontal: 4,
    paddingVertical: 0,
  },
  commentContent: {
    ...DISCUSSION_BODY_TYPOGRAPHY,
  },
  commentMention: {
    ...DISCUSSION_BODY_TYPOGRAPHY,
    fontWeight: '600',
  },
  replyListWrap: {
    marginTop: 0,
    alignSelf: 'stretch',
    // Each reply owns its indentation; the list adds no second inset.
    marginLeft: 0,
    marginRight: 0,
    paddingTop: 0,
    paddingLeft: 0,
    paddingRight: 0,
    gap: 0,
  },
  replySectionHeader: {
    backgroundColor: 'transparent',
    minHeight: 48,
    paddingLeft: 56,
    paddingRight: 20,
    paddingVertical: 0,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    gap: 4,
  },
  replySectionHeaderText: {
    ...typography.role.helper,
    fontWeight: '600',
  },
  replyRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    alignSelf: 'stretch',
    gap: 8,
    paddingTop: 4,
    paddingBottom: 0,
    // Reply avatars align to the root body (20 inset + 28 avatar + 8 gap).
    paddingLeft: 56,
    paddingRight: 20,
    backgroundColor: 'transparent',
  },
  replyMarkerTapTarget: {
    width: 20,
    height: 20,
    marginTop: 2,
    alignItems: 'center',
    justifyContent: 'center',
  },
  replyAvatar: { width: 20, height: 20, borderRadius: 10, borderWidth: 1 },
  replyAvatarFallback: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  replyDivider: {
    height: COMMENT_REPLY_DIVIDER_WIDTH,
    alignSelf: 'stretch',
    backgroundColor: COMMENT_REPLY_DIVIDER_COLOR,
  },
  replyContentWrap: {
    flex: 1,
    minWidth: 0,
  },
  replyTapContent: {
    minHeight: 48,
    alignSelf: 'stretch',
    minWidth: 0,
  },
  replyMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 6,
    marginBottom: 4,
  },
  replyAuthorText: {
    maxWidth: '100%',
    flexShrink: 1,
    ...DISCUSSION_BODY_TYPOGRAPHY,
    fontWeight: '700',
  },
  replyMetaText: {
    ...typography.role.helper,
  },
  replyBubble: {
    borderRadius: 8,
    borderWidth: 0,
    paddingHorizontal: 10,
    paddingVertical: 6,
    alignSelf: 'flex-start',
    maxWidth: '100%',
  },
  replyContent: {
    ...DISCUSSION_BODY_TYPOGRAPHY,
  },
  replyMention: {
    ...DISCUSSION_BODY_TYPOGRAPHY,
    fontWeight: '600',
  },
  replyActionRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: 4,
    marginTop: 0,
    paddingLeft: 0,
  },
  listFooterWrap: {
    paddingHorizontal: 20,
    paddingTop: 6,
    paddingBottom: 8,
  },
  listFooterSpacer: {
    height: 8,
  },
  moreCommentsButton: {
    minHeight: 48,
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  moreCommentsText: {
    ...typography.role.helper,
    fontWeight: '700',
  },
  commentComposerWrap: {
    borderTopWidth: 1,
    paddingHorizontal: 20,
    paddingVertical: 6,
  },
  inlineCommentComposerWrap: {
    alignSelf: 'stretch',
    paddingTop: 4,
    paddingBottom: 8,
  },
  replyComposerBanner: {
    minHeight: 34,
    borderRadius: 12,
    paddingHorizontal: 12,
    marginBottom: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  replyComposerText: {
    flex: 1,
    ...typography.role.helper,
    fontWeight: '600',
  },
  replyComposerMention: {
    fontWeight: '700',
  },
  replyComposerCancel: {
    ...typography.role.helper,
    fontWeight: '700',
  },
  replyCancelTouchTarget: {
    minHeight: 44,
    minWidth: 44,
    paddingHorizontal: 6,
    justifyContent: 'center',
    alignItems: 'center',
  },
  commentComposer: {
    borderWidth: 1,
    borderRadius: 20,
    minHeight: 52,
    paddingLeft: 14,
    paddingRight: 8,
    paddingVertical: 4,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  commentInput: {
    flex: 1,
    minHeight: 44,
    maxHeight: 96,
    ...typography.role.body,
    paddingTop: 4,
    paddingBottom: 4,
    textAlignVertical: 'center',
    includeFontPadding: false,
  },
  commentSubmitButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
  },
  menuBackdrop: {
    flex: 1,
    justifyContent: 'center',
    padding: 20,
  },
  menuScrim: {
    ...StyleSheet.absoluteFill,
  },
  menuSheet: {
    borderWidth: 1,
    borderRadius: 12,
    padding: 12,
    gap: 8,
    maxWidth: 320,
    width: '100%',
    alignSelf: 'center',
  },
  menuAction: {
    minHeight: 44,
    paddingHorizontal: 12,
    paddingVertical: 6,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  menuActionText: {
    fontWeight: '700',
  },
  reportSheet: {
    borderWidth: 1,
    borderRadius: 22,
    padding: 18,
    gap: 14,
    maxWidth: 360,
    width: '100%',
    alignSelf: 'center',
  },
  reportScrollContent: {
    flexGrow: 1,
    justifyContent: 'center',
    paddingVertical: 20,
  },
  reportSheetTouchGuard: {
    width: '100%',
  },
  reportEyebrowWrap: {
    alignSelf: 'flex-start',
    minHeight: 28,
    borderRadius: 999,
    paddingHorizontal: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  reportEyebrow: {
    ...typography.role.caption,
    fontWeight: '800',
    letterSpacing: 0,
  },
  reportTitle: {
    ...typography.role.titleSm,
    fontWeight: '700',
  },
  reportReasonList: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  reportReasonButton: {
    minHeight: 40,
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  reportReasonText: {
    ...typography.role.helper,
    fontWeight: '700',
  },
  reportInput: {
    minHeight: 92,
    borderRadius: 16,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 10,
    textAlignVertical: 'top',
    ...typography.role.bodySm,
  },
  reportActions: {
    flexDirection: 'row',
    gap: 10,
  },
  reportActionButton: {
    flex: 1,
    minHeight: 44,
    borderRadius: 16,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
});
