import { StyleSheet } from 'react-native';
import { typography } from '../../app/theme/tokens/typography';

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  header: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingBottom: 12,
  },
  headerSide: {
    width: 72,
    minHeight: 44,
    alignItems: 'flex-start',
    justifyContent: 'center',
    zIndex: 2,
    elevation: 2,
  },
  headerLeft: {
    width: 92,
  },
  backButton: {
    width: 44,
    height: 44,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  connectedHeaderTitle: {
    ...typography.role.screenTitle,
    fontSize: 18,
    lineHeight: 24,
    fontWeight: '600',
    letterSpacing: 0,
  },
  headerTitle: {
    flex: 1,
    textAlign: 'center',
  },
  centerState: {
    minHeight: 180,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 28,
    paddingVertical: 24,
  },
  errorTitle: {
    marginBottom: 8,
    textAlign: 'center',
    color: '#243042',
  },
  errorBody: {
    textAlign: 'center',
    lineHeight: 22,
    color: '#566271',
  },
  retryButton: {
    marginTop: 18,
    minHeight: 44,
    borderRadius: 999,
    paddingHorizontal: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  retryButtonText: {
    fontWeight: '700',
  },
  listContent: {
    flexGrow: 1,
    paddingBottom: 12,
  },
  listWrap: {
    flex: 1,
  },
  postList: {
    flex: 1,
  },
  heroImage: {
    position: 'absolute',
    top: 0,
    left: 0,
    backgroundColor: '#F1F3F6',
  },
  heroFrame: {
    position: 'relative',
  },
  heroCanvas: {
    position: 'relative',
  },
  heroTail: {
    height: 12,
  },
  heroFallback: {
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20,
    gap: 8,
    backgroundColor: '#F1F3F6',
  },
  categoryHeader: {
    backgroundColor: '#FFFFFF',
    zIndex: 2,
    borderTopLeftRadius: 12,
    borderTopRightRadius: 12,
    marginTop: -12,
    overflow: 'hidden',
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: '#E6E8F0',
  },
  filterBarRow: {
    minHeight: 48,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: '#E6E8F0',
  },
  secondaryCategoryRow: {
    minHeight: 52,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 4,
  },
  filterScroll: {
    flex: 1,
    minWidth: 0,
  },
  categoryRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingRight: 8,
  },
  pageSizeButton: {
    minWidth: 68,
    minHeight: 44,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 3,
    paddingHorizontal: 6,
  },
  categoryChip: {
    minHeight: 44,
    alignItems: 'center',
    justifyContent: 'center',
  },
  categoryChipFace: {
    minHeight: 32,
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 6,
    alignItems: 'center',
    justifyContent: 'center',
  },
  categoryChipLabel: {
    ...typography.role.tab,
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '500',
    letterSpacing: 0,
  },
  filterTab: {
    minHeight: 44,
    paddingHorizontal: 12,
    paddingTop: 8,
    paddingBottom: 8,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  categoryChipText: {
    ...typography.role.tab,
    fontWeight: '500',
    letterSpacing: 0,
  },
  categoryChipTextActive: {
    fontWeight: '600',
    letterSpacing: 0,
  },
  categoryChipUnderline: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    height: 3,
    borderRadius: 2,
  },
  emptyWrap: {
    alignItems: 'center',
    paddingTop: 48,
    paddingHorizontal: 24,
    paddingBottom: 24,
  },
  emptyListContent: {
    flexGrow: 1,
  },
  emptyIcon: {
    width: 54,
    height: 54,
    borderRadius: 27,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
  },
  emptyTitle: {
    marginBottom: 8,
    textAlign: 'center',
    color: '#243042',
  },
  emptyBody: {
    lineHeight: 22,
    textAlign: 'center',
    color: '#566271',
  },
  emptyButton: {
    marginTop: 18,
    minHeight: 44,
    borderRadius: 999,
    paddingHorizontal: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyButtonText: {
    fontWeight: '700',
  },
  footerLoading: {
    paddingVertical: 18,
  },
  inlineListLoading: {
    minHeight: 32,
    alignItems: 'center',
    justifyContent: 'center',
  },
  pageSizeText: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '600',
    letterSpacing: 0,
  },
  paginationFooter: {
    marginTop: 8,
    backgroundColor: '#FFFFFF',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingHorizontal: 16,
    paddingTop: 4,
    paddingBottom: 4,
  },
  paginationControls: {
    flex: 1,
    minWidth: 0,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 16,
  },
  floatingActions: {
    position: 'absolute',
    right: 16,
    bottom: 12,
    gap: 12,
    alignItems: 'center',
    zIndex: 4,
  },
  createButton: {
    width: 48,
    minHeight: 48,
    borderRadius: 24,
    paddingHorizontal: 0,
    paddingVertical: 0,
  },
  paginationButton: {
    minWidth: 44,
    minHeight: 44,
    borderRadius: 6,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 3,
    paddingHorizontal: 14,
    paddingVertical: 0,
    flexShrink: 0,
    borderWidth: 1,
    borderColor: '#D9DDE5',
  },
  paginationButtonText: {
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '600',
    letterSpacing: 0,
  },
  paginationPageIndicator: {
    minWidth: 32,
    minHeight: 44,
    paddingHorizontal: 4,
    backgroundColor: 'transparent',
    alignItems: 'center',
    justifyContent: 'center',
  },
  paginationPageText: {
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '600',
    letterSpacing: 0,
  },
  pageSizeOptions: {
    gap: 8,
  },
  pageSizeOption: {
    minHeight: 56,
    borderRadius: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 12,
  },
  pageSizeOptionText: {
    flexShrink: 1,
    fontWeight: '700',
  },
  topButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    shadowColor: '#0B1220',
    shadowOpacity: 0.12,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 4,
    zIndex: 4,
  },
});
