import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  screen: { flex: 1 },
  ambient: { position: 'absolute', top: 0, right: 0, bottom: 0, left: 0 },
  scroll: { flex: 1 },
  scrollContent: {
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 20,
    gap: 16,
  },
  header: {
    paddingHorizontal: 18,
    paddingBottom: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  headerSideSlot: { width: 44, minHeight: 44, justifyContent: 'center' },
  headerSideSlotRight: { alignItems: 'flex-end' },
  headerBackButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.8)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: { flex: 1, minWidth: 0, textAlign: 'center' },
  emptyCard: { paddingVertical: 24, alignItems: 'center', gap: 12 },
  hero: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    paddingVertical: 4,
  },
  iconWrap: {
    width: 48,
    height: 56,
    alignItems: 'center',
    justifyContent: 'center',
  },
  heroTextWrap: { flex: 1, minWidth: 0, gap: 5 },
  title: { fontWeight: '900', flexShrink: 1 },
  glass: { marginTop: 0, padding: 18 },
  dateBlock: { gap: 5 },
  dateTitle: { fontWeight: '900', flexShrink: 1 },
  timeTitle: { fontWeight: '800', flexShrink: 1 },
  divider: {
    height: 1,
    backgroundColor: 'rgba(69,77,89,0.12)',
    marginVertical: 14,
  },
  metaRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    minHeight: 36,
    gap: 14,
    paddingVertical: 6,
  },
  metaRowCompact: { flexDirection: 'column', gap: 4 },
  metaLabel: { width: 54 },
  metaValue: { flex: 1, minWidth: 0, flexShrink: 1 },
  metaValueCompact: { flex: 0, width: '100%' },
  alarmNotice: { marginTop: 8, gap: 5 },
  alarmAction: { minHeight: 44, paddingVertical: 10, alignSelf: 'flex-start' },
  memo: { gap: 8 },
  linkedSection: { gap: 10 },
  linkedAction: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    minHeight: 64,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.8)',
    borderRadius: 16,
    backgroundColor: 'rgba(255,255,255,0.42)',
    padding: 14,
  },
  linkedText: { flex: 1, minWidth: 0, gap: 4 },
  actions: { gap: 10 },
  actionPair: { flexDirection: 'row', alignItems: 'stretch', gap: 10 },
  actionPairStack: { flexDirection: 'column' },
  pairButton: { flex: 1, minWidth: 0 },
  primaryBtn: {
    minHeight: 50,
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  primaryBtnText: { color: '#FFFFFF', fontWeight: '900' },
  secondaryBtn: {
    minHeight: 48,
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
  },
  secondaryBtnText: { fontWeight: '800' },
  deleteBtn: {
    minHeight: 48,
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  deleteBtnText: { fontWeight: '700' },
  disabled: { opacity: 0.55 },
});
