import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  screen: { flex: 1 },
  ambient: { position: 'absolute', top: 0, right: 0, bottom: 0, left: 0 },
  header: {
    paddingHorizontal: 18,
    paddingBottom: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  headerBackButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.8)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: { flex: 1, minWidth: 0, textAlign: 'center' },
  scroll: { flex: 1 },
  scrollContent: { paddingHorizontal: 20, paddingBottom: 32 },
  subtitle: { marginTop: 8, marginBottom: 14 },
  search: {
    minHeight: 48,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.85)',
    borderRadius: 16,
    backgroundColor: 'rgba(255,255,255,0.56)',
    paddingHorizontal: 12,
  },
  searchInput: { flex: 1, minWidth: 0, minHeight: 46, paddingVertical: 10 },
  clearButton: {
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
  },
  filterRow: {
    flexDirection: 'row',
    gap: 10,
    alignItems: 'center',
    marginTop: 12,
  },
  segments: {
    flex: 1,
    width: '100%',
    flexDirection: 'row',
    padding: 3,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.85)',
    borderRadius: 16,
    backgroundColor: 'rgba(255,255,255,0.30)',
  },
  segment: {
    flex: 1,
    minWidth: 0,
    minHeight: 44,
    paddingHorizontal: 6,
    paddingVertical: 10,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  segmentsGrid: { flexWrap: 'wrap' },
  segmentGrid: { flexBasis: '50%', flexGrow: 0 },
  todayButton: {
    minHeight: 44,
    paddingHorizontal: 6,
    alignItems: 'center',
    justifyContent: 'center',
  },
  monthTitle: { marginTop: 20, marginBottom: 8 },
  dayTitle: { marginTop: 12, marginBottom: 8 },
  card: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.75)',
    paddingHorizontal: 12,
    paddingVertical: 12,
    backgroundColor: 'rgba(255,255,255,0.52)',
    flexDirection: 'row',
    gap: 10,
    alignItems: 'center',
    marginBottom: 8,
  },
  cardTextCol: { flex: 1, minWidth: 0, gap: 4 },
  empty: { paddingVertical: 36, gap: 12, alignItems: 'center' },
  centered: { textAlign: 'center' },
});
