// 파일: src/screens/Records/RecordDetailScreen.styles.ts
// 역할:
// - 원본 비율 사진, 기록 본문, 과거 추억의 단일 세로 목록 레이아웃
// - 상단 헤더, 피드 카드, 액션 메뉴, 삭제 확인 모달 톤을 한 곳에서 관리

import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  header: {
    width: '100%',
    paddingTop: 14,
    paddingBottom: 6,
    backgroundColor: '#F6F7FB',
    alignItems: 'center',
  },
  headerTitle: {
    color: '#111827',
    fontWeight: '800',
    textAlign: 'center',
  },
  headerLink: {
    minHeight: 56,
    paddingHorizontal: 18,
    paddingTop: 8,
    paddingBottom: 8,
    backgroundColor: '#FFFFFF',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  headerSideSlot: {
    width: 44,
    minHeight: 44,
    justifyContent: 'center',
    alignItems: 'flex-start',
  },
  headerSideSlotRight: {
    alignItems: 'flex-end',
  },
  backButton: {
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerLinkText: {
    flex: 1,
    color: '#111827',
    fontWeight: '800',
    textAlign: 'center',
  },
  scroll: {
    flex: 1,
  },
  body: {
    paddingTop: 8,
    paddingBottom: 24,
  },
  relatedSection: {
    marginTop: 20,
    marginHorizontal: 16,
    borderTopWidth: 1,
    borderTopColor: '#E8EBF2',
    paddingTop: 20,
    paddingBottom: 8,
    gap: 12,
  },
  historyRow: { marginHorizontal: 16, marginBottom: 12 },
  historyFooter: { marginHorizontal: 16, gap: 12 },
  fullPhoto: { width: '100%', height: '100%' },
  photoOverlay: {
    flex: 1,
    backgroundColor: 'rgba(12,18,27,0.9)',
    justifyContent: 'center',
  },
  photoClose: {
    position: 'absolute',
    right: 16,
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 22,
    backgroundColor: 'rgba(0,0,0,0.35)',
  },
  relatedSectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  relatedSectionTitle: {
    color: '#111827',
    fontWeight: '800',
  },
  relatedSectionCount: {
    color: '#98A2B3',
    fontWeight: '700',
  },
  relatedEmptyCard: {
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#E8EBF2',
    backgroundColor: '#FFFFFF',
    paddingVertical: 18,
    paddingHorizontal: 14,
    alignItems: 'center',
  },
  relatedEmptyText: {
    color: '#667085',
    fontWeight: '700',
  },
  relatedMoreButton: {
    minHeight: 46,
    borderRadius: 16,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  relatedMoreButtonText: {
    flex: 1,
    textAlign: 'center',
    fontWeight: '800',
  },
  relatedMoreButtonSide: {
    width: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },

  postCard: {
    marginHorizontal: 16,
    backgroundColor: '#FFFFFF',
    borderColor: '#E8EBF2',
  },
  postHeader: {
    minHeight: 60,
    paddingBottom: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  postHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    flex: 1,
  },
  postAvatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: '#F1E1D0',
  },
  postAvatarFallback: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  postAvatarFallbackText: {
    color: '#8B5E3C',
    fontWeight: '700',
  },
  postHeaderTextWrap: {
    flex: 1,
    gap: 2,
  },
  postPetName: {
    color: '#101828',
    fontWeight: '700',
    fontSize: 14,
    lineHeight: 20,
  },
  postMetaLine: {
    color: '#748096',
    fontWeight: '400',
  },
  postMoreBtn: {
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
  },
  postImage: {
    width: '100%',
    height: '100%',
    backgroundColor: '#EFF2F7',
  },
  postImageViewport: {
    width: '100%',
    borderRadius: 18,
    overflow: 'hidden',
  },
  postImageSlide: {
    overflow: 'hidden',
    backgroundColor: '#EFF2F7',
  },
  postImagePager: {
    position: 'absolute',
    top: 12,
    right: 12,
    minHeight: 24,
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 12,
    backgroundColor: 'rgba(12,18,32,0.44)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  postImagePagerText: {
    color: '#FFFFFF',
    fontWeight: '800',
  },
  postImageFallback: {
    width: '100%',
    aspectRatio: 1.55,
    backgroundColor: '#EFF7FD',
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  postImageFallbackText: {
    color: '#748096',
    textAlign: 'center',
  },
  postActions: {
    minHeight: 46,
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  postActionsLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
  },
  postBody: {
    paddingTop: 20,
    gap: 12,
  },
  postTitleText: {
    color: '#111827',
    fontSize: 18,
    lineHeight: 26,
    fontWeight: '700',
  },
  postContentText: {
    color: '#445065',
    fontSize: 13,
    lineHeight: 22,
  },
  postMoodRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  postMoodEmoji: {
    color: '#111827',
  },
  postMoodLabel: {
    color: '#667085',
    fontWeight: '600',
  },
  postTagsText: {
    color: '#7B88A2',
    lineHeight: 18,
    fontWeight: '600',
  },
  postDateText: {
    color: '#9AA4B7',
    fontWeight: '600',
  },

  sheetBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(12,18,32,0.28)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
  },
  sheetDismiss: {
    ...StyleSheet.absoluteFill,
  },
  actionSheet: {
    width: '100%',
    maxWidth: 380,
    borderRadius: 20,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E7EAF1',
    overflow: 'hidden',
    padding: 18,
    gap: 12,
  },
  sheetActionRow: {
    minHeight: 48,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 8,
    paddingHorizontal: 12,
  },
  sheetActionDivider: {
    height: 1,
    backgroundColor: '#EFF2F7',
  },
  sheetActionText: {
    color: '#243042',
    fontWeight: '700',
  },
  sheetActionDeleteText: {
    fontWeight: '700',
  },
  petNameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 8,
  },
  categoryChip: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 12,
    gap: 4,
  },
  categoryText: {
    fontSize: 11,
    lineHeight: 16,
    fontWeight: '600',
    letterSpacing: 0,
  },
  noPhoto: {
    aspectRatio: undefined,
    minHeight: 180,
    paddingHorizontal: 14,
    paddingVertical: 20,
    gap: 10,
  },
  noPhotoTitle: {
    color: '#283F64',
    fontWeight: '600',
    textAlign: 'center',
    fontSize: 13,
    lineHeight: 20,
  },
  imageRetry: {
    minHeight: 44,
    minWidth: 44,
    justifyContent: 'center',
    paddingHorizontal: 12,
  },
  imageDots: {
    position: 'absolute',
    bottom: 12,
    left: 0,
    right: 0,
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 6,
  },
  imageDot: { width: 8, height: 8, borderRadius: 4 },
  tags: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  tagChip: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 14,
    backgroundColor: '#EFF7FD',
    maxWidth: '100%',
  },
  tagText: { color: '#5B7794', fontSize: 11, lineHeight: 16, letterSpacing: 0 },
  relatedCard: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 6,
    marginBottom: 10,
    gap: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#F0F2F5',
    backgroundColor: '#FFFFFF',
  },
  relatedThumb: {
    width: 72,
    height: 80,
    borderRadius: 8,
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
  },
  relatedThumbImage: { width: '100%', height: '100%' },
  relatedBody: { flex: 1, minWidth: 0, gap: 4 },
  relatedTime: { color: '#748096' },
  relatedTitle: { fontSize: 12, lineHeight: 18, letterSpacing: 0 },

  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(12,18,32,0.44)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 26,
  },
  modalCard: {
    width: '100%',
    borderRadius: 28,
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 22,
    paddingTop: 20,
    paddingBottom: 18,
    alignItems: 'center',
  },
  modalIconCircleDanger: {
    width: 58,
    height: 58,
    borderRadius: 29,
    backgroundColor: 'rgba(255,77,79,0.10)',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 14,
  },
  modalTitle: {
    color: '#0B1220',
    fontWeight: '800',
    textAlign: 'center',
    marginBottom: 10,
  },
  modalDesc: {
    color: '#8A94A6',
    textAlign: 'center',
    fontWeight: '600',
    lineHeight: 20,
  },
  modalPrimaryBtn: {
    width: '100%',
    height: 52,
    borderRadius: 26,
    backgroundColor: '#FF4D4F',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 12,
  },
  modalPrimaryBtnText: {
    color: '#FFFFFF',
    fontWeight: '800',
  },
  modalPrimaryBtnDisabled: {
    opacity: 0.6,
  },
  modalGhostBtn: {
    width: '100%',
    height: 52,
    borderRadius: 26,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 20,
    backgroundColor: '#FFFFFF',
  },
  modalGhostBtnText: {
    color: '#667085',
    fontWeight: '700',
  },

  empty: {
    margin: 14,
    backgroundColor: '#FFFFFF',
    borderRadius: 22,
    padding: 18,
    borderWidth: 1,
    borderColor: '#E6E8F0',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    flex: 1,
  },
  emptyTitle: {
    color: '#0B1220',
    fontWeight: '800',
  },
  emptyDesc: {
    color: '#556070',
    textAlign: 'center',
  },
});
