// 파일: src/screens/Records/RecordDetailScreen.styles.ts
import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: '#F6F7FB' },

  header: {
    height: 56,
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: '#E6E8F0',
    backgroundColor: '#FFFFFF',
  },
  backBtn: {
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: {
    flex: 1,
    textAlign: 'center',
    color: '#0B1220',
    fontWeight: '900',
  },
  headerRight: {
    minWidth: 70,
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
    gap: 10,
  },

  scroll: { flex: 1 },
  body: { padding: 14, gap: 12, paddingBottom: 20 },
  heroSlider: {
    borderRadius: 22,
    borderWidth: 1,
    borderColor: '#E6E8F0',
    backgroundColor: '#FFFFFF',
  },
  heroImg: {
    height: 300,
    borderRadius: 22,
    backgroundColor: '#F2F4FA',
  },
  heroPlaceholder: {
    width: '100%',
    height: 300,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: '#E6E8F0',
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  heroPlaceholderText: { color: '#8A94A6', fontWeight: '800' },
  heroPagerBox: {
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: -2,
    gap: 4,
  },
  heroDots: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  heroPagerText: {
    color: '#8A94A6',
    fontWeight: '800',
    minWidth: 34,
    textAlign: 'center',
  },
  heroDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#D8DEEA',
  },
  heroDotActive: {
    width: 16,
    backgroundColor: '#6D6AF8',
  },

  card: {
    backgroundColor: '#FFFFFF',
    borderRadius: 22,
    padding: 16,
    borderWidth: 1,
    borderColor: '#E6E8F0',
  },
  title: { color: '#0B1220', fontWeight: '900' },

  metaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 10,
  },
  metaText: { color: '#8A94A6', fontWeight: '700' },
  categoryBadge: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 999,
    backgroundColor: 'rgba(147,95,255,0.14)',
  },
  categoryBadgeText: {
    color: '#6C4DDB',
    fontWeight: '800',
  },

  moodCard: {
    marginTop: 14,
    minHeight: 56,
    borderRadius: 18,
    backgroundColor: '#F2F4FA',
    borderWidth: 1,
    borderColor: 'rgba(17,24,39,0.04)',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    gap: 10,
  },
  moodIconWrap: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  moodEmoji: { fontSize: 16, color: '#0B1220' },
  moodTextWrap: { flex: 1 },
  moodLabel: { color: '#A1ACBE', fontWeight: '700' },
  moodValue: { color: '#6D6AF8', fontWeight: '900' },

  contentBox: {
    marginTop: 14,
    minHeight: 140,
  },
  tags: { marginTop: 14, color: '#6D7CFF', fontWeight: '800' },
  content: { color: '#556070', lineHeight: 22 },
  simpleActionBtn: {
    minHeight: 24,
    justifyContent: 'center',
  },
  simpleActionText: {
    color: '#6E7B90',
    fontWeight: '700',
  },
  simpleActionTextDisabled: {
    color: '#9AA4B7',
  },
  simpleDeleteText: {
    color: '#FF5A5F',
  },
  cardOutsideActionRow: {
    marginTop: 6,
    paddingHorizontal: 2,
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
    gap: 14,
  },
  feedSection: {
    gap: 12,
    marginTop: 8,
  },
  feedHeader: {
    paddingHorizontal: 2,
    gap: 4,
  },
  feedSectionTitle: {
    color: '#0B1220',
    fontWeight: '800',
  },
  feedSectionCaption: {
    color: '#8A94A6',
    fontWeight: '700',
  },
  feedList: {
    gap: 10,
  },
  feedCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#E6E8F0',
    overflow: 'hidden',
  },
  feedCardImage: {
    width: '100%',
    height: 198,
    backgroundColor: '#EEF1F7',
  },
  feedCardImageFallback: {
    width: '100%',
    height: 158,
    backgroundColor: '#F2F4FA',
    alignItems: 'center',
    justifyContent: 'center',
  },
  feedCardImageFallbackText: {
    color: '#9AA4B7',
    fontWeight: '700',
  },
  feedCardBody: {
    padding: 15,
    gap: 10,
  },
  feedMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  feedBadge: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 999,
    backgroundColor: 'rgba(147,95,255,0.10)',
  },
  feedBadgeText: {
    color: '#6C4DDB',
    fontWeight: '800',
  },
  feedDate: {
    color: '#99A3B5',
    fontWeight: '700',
  },
  feedTitle: {
    color: '#192132',
    fontWeight: '800',
  },
  feedPreview: {
    color: '#667284',
    lineHeight: 18,
  },
  feedLoading: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 10,
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(12,18,32,0.44)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 26,
  },
  modalCard: {
    width: '100%',
    borderRadius: 28,
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 22,
    paddingTop: 20,
    paddingBottom: 18,
    alignItems: 'center',
  },
  modalIconCircleDanger: {
    width: 58,
    height: 58,
    borderRadius: 29,
    backgroundColor: 'rgba(255,77,79,0.10)',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 14,
  },
  modalTitle: {
    color: '#0B1220',
    fontWeight: '900',
    textAlign: 'center',
    marginBottom: 10,
  },
  modalDesc: {
    color: '#8A94A6',
    textAlign: 'center',
    fontWeight: '700',
    lineHeight: 20,
  },
  modalPrimaryBtn: {
    width: '100%',
    height: 52,
    borderRadius: 26,
    backgroundColor: '#6D6AF8',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 20,
    shadowColor: '#5D57E8',
    shadowOpacity: 0.26,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 5,
  },
  modalPrimaryBtnText: {
    color: '#FFFFFF',
    fontWeight: '900',
  },
  modalGhostBtn: {
    marginTop: 12,
    minHeight: 28,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalGhostBtnText: {
    color: '#9AA4B7',
    fontWeight: '800',
  },

  empty: {
    margin: 14,
    backgroundColor: '#FFFFFF',
    borderRadius: 22,
    padding: 18,
    borderWidth: 1,
    borderColor: '#E6E8F0',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    flex: 1,
  },
  emptyTitle: { color: '#0B1220', fontWeight: '900' },
  emptyDesc: { color: '#556070', textAlign: 'center' },
});
