import { StyleSheet } from 'react-native';

export const createFormStyles = StyleSheet.create({
  categories: { flexDirection: 'row', flexWrap: 'wrap', gap: 4 },
  categoryTouch: { minWidth: 52, minHeight: 48, justifyContent: 'center' },
  categoryFace: {
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 16,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  categoryText: { fontSize: 14, lineHeight: 20, fontWeight: '600' },
  policy: { borderRadius: 8, overflow: 'hidden' },
  policyToggle: {
    minHeight: 48,
    paddingHorizontal: 12,
    paddingVertical: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  policyTitle: { flex: 1, fontSize: 14, lineHeight: 20, fontWeight: '600' },
  policyBody: { paddingHorizontal: 12, paddingBottom: 4, gap: 4 },
  policyCopy: { fontSize: 14, lineHeight: 22 },
  policyAction: {
    minHeight: 48,
    alignSelf: 'flex-start',
    justifyContent: 'center',
  },
  policyActionText: { fontSize: 13, lineHeight: 20, fontWeight: '600' },
  titleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    minHeight: 60,
    gap: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
  },
  titleLabel: { fontSize: 16, lineHeight: 24, fontWeight: '600' },
  titleInput: {
    flex: 1,
    minWidth: 0,
    minHeight: 48,
    fontSize: 16,
    lineHeight: 24,
    paddingHorizontal: 0,
    paddingVertical: 8,
    textAlignVertical: 'center',
  },
  bodySection: { flexGrow: 1, minHeight: 240, gap: 4 },
  bodyInput: {
    flexGrow: 1,
    minHeight: 216,
    fontSize: 16,
    lineHeight: 26,
    padding: 0,
    textAlignVertical: 'top',
  },
  counter: { alignSelf: 'flex-end', fontSize: 11, lineHeight: 18 },
  thumbnails: { flex: 1, flexDirection: 'row', flexWrap: 'wrap', gap: 4 },
  thumbnail: { width: '100%', height: '100%', borderRadius: 8 },
  removeTouch: {
    position: 'absolute',
    top: 0,
    right: 0,
    width: 48,
    height: 48,
    alignItems: 'flex-end',
    padding: 4,
  },
  removeFace: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#243042',
    justifyContent: 'center',
    alignItems: 'center',
  },
  attachmentToolbar: {
    minHeight: 48,
    borderTopWidth: StyleSheet.hairlineWidth,
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
    paddingTop: 8,
    paddingBottom: 8,
    paddingHorizontal: 16,
    gap: 8,
  },
  photoAction: {
    width: 48,
    minHeight: 48,
    paddingHorizontal: 4,
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 2,
  },
  photoCount: { fontSize: 12, lineHeight: 18 },
  disabled: { opacity: 0.45 },
});
