import { StyleSheet } from 'react-native';

const BRAND = '#6D6AF8';
const BRAND_DEEP = '#5753E6';
const TEXT = '#0B1220';
const MUTED = '#556070';
const SURFACE = '#FFFFFF';
const SURFACE_SOFT = '#F6F7FB';
const BORDER = 'rgba(109,106,248,0.18)';
const BORDER_SOFT = 'rgba(0,0,0,0.06)';

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: SURFACE },
  scroll: { flex: 1, backgroundColor: SURFACE },
  scrollContent: {
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: 34,
    gap: 20,
  },

  header: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
  },
  headerTextArea: { gap: 4, paddingTop: 2, flex: 1 },
  title: { color: TEXT, fontWeight: '900', fontSize: 16, lineHeight: 21 },
  subTitle: {
    color: MUTED,
    fontWeight: '700',
    fontSize: 12,
    lineHeight: 16,
  },
  headerIcons: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  headerIconBtn: {
    width: 34,
    height: 34,
    borderRadius: 999,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(0,0,0,0.04)',
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.04)',
  },
  petSwitcherRow: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  petChip: {
    width: 40,
    height: 40,
    borderRadius: 999,
    overflow: 'hidden',
    backgroundColor: SURFACE_SOFT,
    borderWidth: 1,
    borderColor: BORDER_SOFT,
  },
  petChipActive: {
    borderColor: BRAND,
    borderWidth: 2,
    shadowColor: BRAND,
    shadowOpacity: 0.18,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 6 },
    elevation: 2,
  },
  petChipImage: { width: '100%', height: '100%' },
  petAddChip: {
    width: 40,
    height: 40,
    borderRadius: 999,
    backgroundColor: 'rgba(0,0,0,0.04)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: BORDER_SOFT,
  },
  petAddPlus: {
    color: BRAND_DEEP,
    fontWeight: '900',
    marginTop: -2,
  },

  heroCard: {
    borderRadius: 22,
    padding: 16,
    backgroundColor: SURFACE,
    borderWidth: 1,
    borderColor: BORDER,
    shadowColor: '#000000',
    shadowOpacity: 0.08,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 12 },
    elevation: 5,
  },
  heroCenter: {
    alignItems: 'center',
    paddingTop: 10,
    gap: 6,
  },
  heroAvatarOuter: {
    width: 156,
    height: 156,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 6,
  },
  heroAvatarGlow: {
    position: 'absolute',
    width: 154,
    height: 154,
    borderRadius: 999,
    backgroundColor: 'rgba(87,83,230,0.18)',
    shadowColor: BRAND_DEEP,
    shadowOpacity: 0.22,
    shadowRadius: 32,
    shadowOffset: { width: 0, height: 0 },
    elevation: 9,
  },
  heroAvatarRing: {
    width: 144,
    height: 144,
    borderRadius: 999,
    padding: 6,
    shadowColor: BRAND_DEEP,
    shadowOpacity: 0.2,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 0 },
    elevation: 6,
  },
  heroAvatarRingInner: {
    flex: 1,
    borderRadius: 999,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.84)',
  },
  heroAvatarWrap: {
    width: 132,
    height: 132,
    borderRadius: 999,
    overflow: 'hidden',
    borderWidth: 4,
    borderColor: 'rgba(255,255,255,0.96)',
    backgroundColor: 'rgba(87,83,230,0.08)',
  },
  heroAvatarImg: { width: '100%', height: '100%' },
  heroName: {
    color: TEXT,
    fontWeight: '900',
    textAlign: 'center',
    fontSize: 16,
    lineHeight: 22,
  },
  heroMetaLine: {
    color: MUTED,
    fontWeight: '800',
    textAlign: 'center',
    fontSize: 14,
    lineHeight: 20,
  },
  heroMetaMuted: {
    color: 'rgba(85,96,112,0.65)',
    fontWeight: '800',
    textAlign: 'center',
    fontSize: 12,
    lineHeight: 16,
  },
  heroTogetherPill: {
    marginTop: 12,
    alignSelf: 'center',
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 999,
    backgroundColor: BRAND_DEEP,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.20)',
    shadowColor: '#000000',
    shadowOpacity: 0.16,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 9,
  },
  heroTogetherText: {
    color: '#FFFFFF',
    fontWeight: '900',
    fontSize: 12,
  },
  primaryButton: {
    marginTop: 14,
    width: '100%',
    height: 52,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: BRAND,
  },
  primaryButtonText: {
    color: '#FFFFFF',
    fontWeight: '900',
    fontSize: 15,
  },

  section: { gap: 8 },
  sectionHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  sectionTitle: {
    color: TEXT,
    fontWeight: '900',
    fontSize: 16,
    lineHeight: 21,
  },
  sectionSubTitle: {
    color: MUTED,
    fontWeight: '700',
    fontSize: 12,
    lineHeight: 16,
    marginTop: -2,
  },

  shortcutRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 10,
  },
  shortcutItem: {
    flex: 1,
    alignItems: 'center',
    gap: 8,
    paddingVertical: 8,
  },
  shortcutIconWrap: {
    width: 48,
    height: 48,
    borderRadius: 999,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(109,106,248,0.08)',
  },
  shortcutLabel: {
    color: MUTED,
    fontWeight: '800',
    textAlign: 'center',
    fontSize: 12,
    lineHeight: 16,
  },

  previewRow: {
    paddingTop: 4,
    paddingRight: 16,
    gap: 12,
  },
  previewCard: {
    width: 238,
    height: 238,
    borderRadius: 24,
    overflow: 'hidden',
    backgroundColor: SURFACE_SOFT,
  },
  previewImage: {
    width: '100%',
    height: '100%',
  },
  previewOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(11,18,32,0.26)',
  },
  previewTextWrap: {
    position: 'absolute',
    left: 16,
    right: 16,
    bottom: 16,
    gap: 4,
  },
  previewEyebrow: {
    color: 'rgba(255,255,255,0.82)',
    fontWeight: '900',
    fontSize: 12,
  },
  previewTitle: {
    color: '#FFFFFF',
    fontWeight: '900',
    fontSize: 15,
    lineHeight: 21,
  },

  tipList: {
    paddingTop: 4,
    gap: 12,
  },
  tipCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    padding: 14,
    borderRadius: 22,
    backgroundColor: SURFACE,
    borderWidth: 1,
    borderColor: BORDER_SOFT,
  },
  tipThumb: {
    width: 72,
    height: 72,
    borderRadius: 18,
    backgroundColor: SURFACE_SOFT,
  },
  tipContent: {
    flex: 1,
    gap: 4,
  },
  tipEyebrow: {
    color: BRAND,
    fontWeight: '900',
    fontSize: 12,
  },
  tipTitle: {
    color: TEXT,
    fontWeight: '800',
    fontSize: 15,
    lineHeight: 21,
  },
  tipDescription: {
    color: MUTED,
    fontWeight: '700',
    fontSize: 12,
    lineHeight: 17,
  },

  activityList: {
    paddingTop: 4,
    gap: 10,
  },
  activityCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingHorizontal: 14,
    paddingVertical: 14,
    borderRadius: 18,
    backgroundColor: SURFACE,
    borderWidth: 1,
    borderColor: BORDER_SOFT,
  },
  activityIconWrap: {
    width: 38,
    height: 38,
    borderRadius: 999,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(109,106,248,0.08)',
  },
  activityTextCol: {
    flex: 1,
    gap: 4,
  },
  activityTitle: {
    color: TEXT,
    fontWeight: '800',
    fontSize: 15,
    lineHeight: 20,
  },
  activitySub: {
    color: MUTED,
    fontWeight: '700',
    fontSize: 12,
    lineHeight: 16,
  },
  activityTime: {
    color: 'rgba(85,96,112,0.76)',
    fontWeight: '800',
    fontSize: 12,
  },

  diaryRow: {
    paddingTop: 4,
    paddingRight: 16,
    gap: 12,
  },
  diaryCard: {
    width: 104,
    height: 104,
    borderRadius: 22,
    backgroundColor: '#E8E2D7',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 14,
  },
  diaryThumb: {
    width: '100%',
    height: '100%',
    borderRadius: 12,
  },
});
