// 파일: src/components/records/FrequentRecordsSection.styles.ts
// 목적: 자주 쓰는 기록 섹션의 평면 레이아웃과 동일한 가로 위젯 토큰을 관리한다.

import { StyleSheet } from 'react-native';

import { typography } from '../../app/theme/tokens/typography';

export const styles = StyleSheet.create({
  section: {
    width: '100%',
  },
  headerRow: {
    minHeight: 44,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
    marginBottom: 14,
  },
  headerLead: {
    flex: 1,
    minWidth: 0,
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
  },
  sparkleWrap: {
    width: 26,
    height: 26,
    borderRadius: 9,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTextGroup: {
    flex: 1,
    minWidth: 0,
    gap: 3,
  },
  title: {
    ...typography.unified.title,
    fontSize: 18,
    lineHeight: 23,
    fontWeight: '600',
    letterSpacing: 0,
  },
  subtitle: {
    ...typography.unified.body,
    fontSize: 10,
    lineHeight: 14,
    fontWeight: '400',
    color: '#7C8495',
  },
  grid: {
    flexDirection: 'column',
    gap: 10,
  },
  recordCard: {
    width: '100%',
    minWidth: 0,
    height: 72,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(124,132,149,0.22)',
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'flex-start',
    backgroundColor: 'transparent',
    shadowOpacity: 0,
    elevation: 0,
  },
  recordCardPressed: {
    opacity: 0.93,
    transform: [{ scale: 0.985 }],
  },
  recordContentStack: {
    width: '100%',
    flex: 1,
    minWidth: 0,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  recordIconSlot: {
    width: 38,
    height: 38,
    flexShrink: 0,
    alignItems: 'center',
    justifyContent: 'center',
  },
  recordIconWrap: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
  },
  recordTextGroup: {
    flex: 1,
    minWidth: 0,
    marginLeft: 11,
    justifyContent: 'center',
  },
  recordTitleSlot: {
    minHeight: 18,
    alignItems: 'flex-start',
    justifyContent: 'center',
  },
  recordLabel: {
    ...typography.unified.label,
    maxWidth: '100%',
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '500',
    color: '#1E2A43',
    textAlign: 'left',
  },
  relativeTimeMarker: {
    minHeight: 16,
    maxWidth: 82,
    paddingHorizontal: 4,
    paddingVertical: 0,
    borderRadius: 2,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  relativeTimePlaceholder: {
    height: 18,
  },
  recordTimeSlot: {
    minWidth: 58,
    minHeight: 18,
    marginLeft: 8,
    flexShrink: 0,
    alignItems: 'flex-end',
    justifyContent: 'center',
  },
  relativeTimeText: {
    ...typography.unified.body,
    fontSize: 9,
    lineHeight: 12,
    fontWeight: '500',
    flexShrink: 1,
    textAlign: 'center',
  },
  recordSummary: {
    ...typography.unified.body,
    width: '100%',
    minHeight: 24,
    fontSize: 9,
    lineHeight: 12,
    fontWeight: '500',
    color: '#5C6677',
    textAlign: 'left',
  },
  recordSummarySlot: {
    width: '100%',
    minHeight: 14,
    marginTop: 2,
    alignItems: 'flex-start',
    justifyContent: 'center',
  },
  statusBox: {
    minHeight: 72,
    alignItems: 'center',
    justifyContent: 'center',
  },
  statusText: {
    ...typography.unified.label,
    fontSize: 13,
    lineHeight: 19,
    fontWeight: '500',
    color: '#7C8495',
    textAlign: 'center',
  },
});
