// 파일: src/components/records/FrequentRecordsSection.styles.ts
// 목적: 자주 쓰는 기록 섹션의 평면 2x2 정사각 그리드 토큰을 관리한다.

import { StyleSheet } from 'react-native';

import { typography } from '../../app/theme/tokens/typography';

export const styles = StyleSheet.create({
  section: {
    width: '100%',
  },
  headerRow: {
    minHeight: 44,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
    marginBottom: 14,
  },
  headerLead: {
    flex: 1,
    minWidth: 0,
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
  },
  sparkleWrap: {
    width: 26,
    height: 26,
    borderRadius: 9,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTextGroup: {
    flex: 1,
    minWidth: 0,
    gap: 3,
  },
  title: {
    ...typography.unified.title,
    fontSize: 18,
    lineHeight: 23,
    fontWeight: '600',
    letterSpacing: 0,
  },
  subtitle: {
    ...typography.unified.body,
    fontSize: 10,
    lineHeight: 14,
    fontWeight: '400',
    color: '#7C8495',
  },
  grid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    rowGap: 10,
    justifyContent: 'space-between',
  },
  recordCard: {
    width: '48%',
    minWidth: 0,
    aspectRatio: 1,
    paddingHorizontal: 8,
    paddingVertical: 8,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(124,132,149,0.22)',
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'transparent',
    shadowOpacity: 0,
    elevation: 0,
  },
  recordCardPressed: {
    opacity: 0.93,
    transform: [{ scale: 0.985 }],
  },
  recordContentStack: {
    width: '100%',
    flex: 1,
    minWidth: 0,
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
  },
  recordIconSlot: {
    width: '100%',
    height: 44,
    flexShrink: 0,
    alignItems: 'center',
    justifyContent: 'center',
  },
  recordIconWrap: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  recordTitleSlot: {
    minHeight: 20,
    marginTop: 6,
    alignItems: 'center',
    justifyContent: 'center',
  },
  recordLabel: {
    ...typography.unified.label,
    maxWidth: '100%',
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '500',
    color: '#1E2A43',
    textAlign: 'center',
  },
  relativeTimeMarker: {
    minHeight: 18,
    maxWidth: '100%',
    paddingHorizontal: 4,
    paddingVertical: 0,
    borderRadius: 2,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  relativeTimePlaceholder: {
    height: 18,
  },
  recordTimeSlot: {
    minHeight: 18,
    marginTop: 6,
    alignItems: 'center',
    justifyContent: 'center',
  },
  relativeTimeText: {
    ...typography.unified.body,
    fontSize: 9,
    lineHeight: 12,
    fontWeight: '500',
    flexShrink: 1,
    textAlign: 'center',
  },
  recordSummary: {
    ...typography.unified.body,
    width: '100%',
    minHeight: 30,
    fontSize: 11,
    lineHeight: 14,
    fontWeight: '500',
    color: '#5C6677',
    textAlign: 'center',
  },
  recordSummarySlot: {
    width: '100%',
    minHeight: 30,
    marginTop: 6,
    alignItems: 'center',
    justifyContent: 'center',
  },
  statusBox: {
    minHeight: 160,
    alignItems: 'center',
    justifyContent: 'center',
  },
  statusText: {
    ...typography.unified.label,
    fontSize: 13,
    lineHeight: 19,
    fontWeight: '500',
    color: '#7C8495',
    textAlign: 'center',
  },
});
