// 파일: src/components/records/FrequentRecordsSection.styles.ts
// 목적: 자주 쓰는 기록 섹션의 프리미엄 카드 토큰과 작은 화면 레이아웃을 관리한다.

import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  outerCard: {
    width: '100%',
    borderRadius: 30,
    padding: 1.25,
    shadowColor: '#7E7AA8',
    shadowOpacity: 0.12,
    shadowRadius: 22,
    shadowOffset: { width: 0, height: 10 },
    elevation: 3,
  },
  innerCard: {
    borderRadius: 29,
    paddingHorizontal: 18,
    paddingVertical: 20,
    backgroundColor: 'rgba(255,255,255,0.96)',
  },
  headerRow: {
    minHeight: 44,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
    marginBottom: 20,
  },
  headerLead: {
    flex: 1,
    minWidth: 0,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  sparkleWrap: {
    width: 38,
    height: 38,
    borderRadius: 13,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTextGroup: {
    flex: 1,
    minWidth: 0,
    gap: 3,
  },
  title: {
    fontSize: 22,
    lineHeight: 29,
    fontWeight: '700',
    letterSpacing: 0,
  },
  subtitle: {
    fontSize: 9,
    lineHeight: 13,
    fontWeight: '400',
    color: '#7C8495',
  },
  allButton: {
    minHeight: 42,
    minWidth: 106,
    paddingHorizontal: 14,
    borderRadius: 21,
    borderWidth: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
  },
  allButtonText: {
    fontSize: 14,
    lineHeight: 19,
    fontWeight: '600',
  },
  allButtonPressed: {
    opacity: 0.9,
    transform: [{ scale: 0.98 }],
  },
  grid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  gridCompact: {
    gap: 12,
  },
  recordCard: {
    width: '23.4%',
    minHeight: 174,
    paddingHorizontal: 8,
    paddingVertical: 15,
    borderRadius: 24,
    alignItems: 'center',
    justifyContent: 'flex-start',
    backgroundColor: 'rgba(250,250,255,0.74)',
    borderWidth: 1,
    shadowColor: '#8C8AA9',
    shadowOpacity: 0.06,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 5 },
    elevation: 1,
  },
  recordCardCompact: {
    width: '47.2%',
    minHeight: 174,
  },
  recordCardPressed: {
    opacity: 0.93,
    transform: [{ scale: 0.985 }],
  },
  recordIconWrap: {
    width: 68,
    height: 68,
    borderRadius: 34,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  recordLabel: {
    maxWidth: '100%',
    fontSize: 18,
    lineHeight: 24,
    fontWeight: '700',
    color: '#1E2A43',
    textAlign: 'center',
  },
  relativeTimePill: {
    minHeight: 30,
    maxWidth: '100%',
    marginTop: 11,
    paddingHorizontal: 9,
    borderRadius: 15,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 5,
  },
  relativeTimePlaceholder: {
    height: 30,
    marginTop: 11,
  },
  relativeTimeText: {
    fontSize: 12,
    lineHeight: 17,
    fontWeight: '600',
    flexShrink: 1,
  },
  recordSummary: {
    width: '100%',
    minHeight: 40,
    marginTop: 10,
    fontSize: 13,
    lineHeight: 19,
    fontWeight: '500',
    color: '#5C6677',
    textAlign: 'center',
  },
  statusBox: {
    minHeight: 174,
    alignItems: 'center',
    justifyContent: 'center',
  },
  statusText: {
    fontSize: 13,
    lineHeight: 19,
    fontWeight: '500',
    color: '#7C8495',
    textAlign: 'center',
  },
});
