import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  section: {
    gap: 20,
    marginTop: 0,
    paddingTop: 20,
    paddingBottom: 14,
    paddingHorizontal: 14,
  },
  panel: {
    paddingHorizontal: 18,
    paddingTop: 18,
    paddingBottom: 18,
    borderRadius: 16,
    borderWidth: 1,
    gap: 14,
  },
  titleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  title: {
    flex: 1,
    flexShrink: 1,
    minWidth: 0,
  },
  pillContent: {
    gap: 8,
    paddingRight: 2,
  },
  pillTouch: {
    minHeight: 44,
    paddingVertical: 4,
    justifyContent: 'center',
  },
  pillVisual: {
    minHeight: 36,
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: 18,
    borderWidth: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  pillText: {
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '600',
  },
  content: {
    gap: 12,
  },
  postList: {
    gap: 0,
  },
  postRow: {
    minHeight: 76,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    borderRadius: 10,
  },
  position: {
    width: 30,
    textAlign: 'center',
    fontSize: 24,
    lineHeight: 30,
    fontWeight: '700',
  },
  postBody: {
    flex: 1,
    minWidth: 0,
    gap: 6,
  },
  featuredTitle: {
    fontSize: 16,
    lineHeight: 22,
    fontWeight: '600',
  },
  supportTitle: {
    fontSize: 15,
    lineHeight: 21,
    fontWeight: '600',
  },
  metadata: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    flexWrap: 'wrap',
  },
  category: {
    fontSize: 12,
    lineHeight: 18,
    fontWeight: '600',
  },
  metadataText: {
    fontSize: 12,
    lineHeight: 18,
    fontWeight: '500',
  },
  separator: {
    height: 1,
    marginLeft: 44,
    opacity: 0.8,
  },
  allButton: {
    minHeight: 44,
    width: '100%',
    paddingHorizontal: 16,
    borderRadius: 12,
    borderWidth: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  allButtonText: {
    fontSize: 15,
    lineHeight: 22,
    fontWeight: '600',
  },
  stateBox: {
    minHeight: 112,
    paddingHorizontal: 16,
    paddingVertical: 18,
    borderRadius: 16,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  stateText: {
    fontSize: 15,
    lineHeight: 22,
    fontWeight: '500',
    textAlign: 'center',
  },
  retryButton: {
    minHeight: 44,
    paddingHorizontal: 16,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  retryText: {
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '700',
  },
  skeletonList: {
    gap: 0,
  },
  skeletonRow: {
    minHeight: 76,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
  },
  skeletonNumber: {
    width: 30,
    height: 26,
    borderRadius: 5,
  },
  skeletonText: {
    flex: 1,
    gap: 8,
  },
  skeletonLine: {
    width: '88%',
    height: 16,
    borderRadius: 8,
    opacity: 0.45,
  },
  skeletonShortLine: {
    width: '42%',
    height: 12,
    borderRadius: 6,
    opacity: 0.45,
  },
});
