import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  section: {
    gap: 12,
    paddingTop: 20,
    paddingBottom: 14,
    paddingHorizontal: 14,
  },
  header: {
    minHeight: 44,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  title: {
    flex: 1,
    minWidth: 0,
    fontSize: 18,
    lineHeight: 24,
    fontWeight: '600',
  },
  allButton: {
    minHeight: 44,
    minWidth: 88,
    paddingHorizontal: 10,
    borderRadius: 12,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 3,
  },
  allButtonText: {
    fontSize: 12,
    lineHeight: 18,
    fontWeight: '600',
  },
  content: {
    gap: 10,
  },
  featuredCard: {
    minHeight: 136,
    padding: 16,
    borderRadius: 16,
    borderWidth: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  featuredIconWrap: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
  },
  postBody: {
    flex: 1,
    minWidth: 0,
    gap: 5,
  },
  category: {
    fontSize: 12,
    lineHeight: 18,
    fontWeight: '600',
  },
  featuredTitle: {
    fontSize: 18,
    lineHeight: 24,
    fontWeight: '700',
    flexShrink: 1,
  },
  supportList: {
    gap: 8,
  },
  supportRow: {
    minHeight: 64,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 14,
    borderWidth: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  supportIconWrap: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
  },
  supportTitle: {
    fontSize: 15,
    lineHeight: 21,
    fontWeight: '600',
    flexShrink: 1,
  },
  metadata: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flexWrap: 'wrap',
  },
  metadataText: {
    fontSize: 11,
    lineHeight: 16,
    fontWeight: '500',
  },
  metadataSeparator: {
    fontSize: 11,
    lineHeight: 16,
    fontWeight: '500',
  },
  arrowSlot: {
    width: 24,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
  },
  stateBox: {
    minHeight: 112,
    paddingHorizontal: 16,
    paddingVertical: 18,
    borderRadius: 16,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  stateText: {
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '500',
    textAlign: 'center',
  },
  retryButton: {
    minHeight: 44,
    paddingHorizontal: 16,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  retryText: {
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '700',
  },
  skeletonFeatured: {
    minHeight: 136,
    padding: 16,
    borderRadius: 16,
    borderWidth: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  skeletonIcon: {
    width: 44,
    height: 44,
    borderRadius: 22,
  },
  skeletonText: {
    flex: 1,
    gap: 8,
  },
  skeletonLine: {
    height: 14,
    borderRadius: 7,
  },
  skeletonShortLine: {
    width: '48%',
    height: 12,
    borderRadius: 6,
  },
  skeletonSupportList: {
    gap: 8,
  },
  skeletonSupport: {
    minHeight: 64,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 14,
    borderWidth: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  skeletonSupportIcon: {
    width: 34,
    height: 34,
    borderRadius: 17,
  },
});
