import { StyleSheet } from 'react-native';

import { spacing } from '../../app/theme/tokens/spacing';

const BRAND = '#6D6AF8';
const BRAND_DEEP = '#5A57E7';
const TEXT = '#352B25';
const MUTED = '#786B61';
const SURFACE = '#FBF3E7';
const FIELD = 'rgba(255, 253, 249, 0.78)';
const BORDER = 'rgba(109,106,248,0.16)';

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: SURFACE,
  },
  backgroundImage: {
    ...StyleSheet.absoluteFill,
    width: '100%',
    height: '100%',
  },
  backgroundWarmth: {
    ...StyleSheet.absoluteFill,
  },
  topReadabilityVeil: {
    position: 'absolute',
    top: 0,
    right: 0,
    left: 0,
    height: '43%',
  },
  continuationCanvas: {
    ...StyleSheet.absoluteFill,
    backgroundColor: '#FAEEDC',
  },
  topChrome: {
    backgroundColor: 'transparent',
    zIndex: 4,
  },
  header: {
    minHeight: 48,
    paddingHorizontal: 18,
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 0,
  },
  headerAction: {
    minWidth: 40,
    height: 32,
    alignItems: 'flex-start',
    justifyContent: 'center',
  },
  headerActionText: {
    color: '#7F8899',
    fontSize: 13,
    fontWeight: '700',
  },
  headerActionPlaceholder: {
    width: 40,
    height: 32,
  },
  fontSelectField: {
    minHeight: 48,
    paddingHorizontal: 14,
    paddingVertical: 12,
    gap: 10,
  },
  fontSelectValue: {
    flex: 1,
    minWidth: 0,
  },
  headerTitle: {
    flex: 1,
    textAlign: 'center',
    color: '#273241',
    fontSize: 16,
    fontWeight: '900',
    textShadowColor: 'rgba(255, 255, 255, 0.72)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 5,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 18,
    paddingTop: 10,
    paddingBottom: 24,
    gap: 16,
  },
  progressHeader: {
    gap: 6,
    paddingHorizontal: 26,
    paddingTop: 2,
    paddingBottom: 10,
    backgroundColor: 'transparent',
  },
  progressMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  progressMain: {
    width: '100%',
  },
  progressLabel: {
    color: TEXT,
    fontSize: 13,
    fontWeight: '800',
    textShadowColor: 'rgba(255, 255, 255, 0.68)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 4,
  },
  progressTrack: {
    width: '100%',
    height: 4,
    borderRadius: 999,
    backgroundColor: 'rgba(255,255,255,0.58)',
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    borderRadius: 999,
    backgroundColor: BRAND,
  },
  progressFillHalf: {
    width: '50%',
  },
  progressFillFull: {
    width: '100%',
  },
  progressStepText: {
    color: BRAND,
    fontSize: 12,
    fontWeight: '800',
    textAlign: 'right',
  },
  card: {
    backgroundColor: 'transparent',
    borderRadius: 28,
    marginTop: 4,
    paddingHorizontal: 18,
    paddingTop: 22,
    paddingBottom: 20,
    gap: 14,
    // shadowColor: '#0A0F1C',
    shadowOpacity: 0.04,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 0,
  },
  avatarSection: {
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 4,
    marginBottom: 2,
    gap: 5,
  },
  avatarHalo: {
    width: 140,
    height: 140,
    borderRadius: 999,
    padding: 5,
    alignItems: 'center',
    justifyContent: 'center',
    shadowOpacity: 0.2,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 8 },
    elevation: 6,
  },
  avatarCircle: {
    width: 130,
    height: 130,
    borderRadius: 999,
    borderWidth: 3,
    borderColor: BRAND,
    backgroundColor: 'rgba(255,253,249,0.82)',
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarPlaceholder: {
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
  },
  avatarPlaceholderText: {
    fontSize: 12,
    fontWeight: '800',
  },
  avatarImage: {
    width: '100%',
    height: '100%',
  },
  avatarEditButton: {
    position: 'absolute',
    right: 2,
    bottom: 8,
    width: 32,
    height: 32,
    borderRadius: 999,
    backgroundColor: BRAND,
    borderWidth: 2,
    borderColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  heroCopy: {
    textAlign: 'center',
    color: TEXT,
    fontSize: 19,
    lineHeight: 25,
    fontWeight: '900',
    marginTop: 6,
    textShadowColor: 'rgba(255, 255, 255, 0.76)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 6,
  },
  heroHelper: {
    color: MUTED,
    fontSize: 12,
    lineHeight: 18,
    fontWeight: '700',
    textAlign: 'center',
  },
  continuationIntro: {
    paddingHorizontal: 4,
    paddingVertical: 10,
    gap: 5,
  },
  continuationTitle: {
    color: TEXT,
    fontSize: 20,
    lineHeight: 27,
    fontWeight: '900',
  },
  continuationBody: {
    color: MUTED,
    fontSize: 12,
    lineHeight: 18,
    fontWeight: '700',
  },
  sectionGlass: {
    borderRadius: 22,
    paddingHorizontal: 17,
    paddingVertical: 17,
    gap: 14,
    backgroundColor: 'rgba(255, 252, 246, 0.70)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.72)',
    overflow: 'hidden',
  },
  sectionHeader: {
    gap: 3,
  },
  sectionTitle: {
    color: TEXT,
    fontSize: 18,
    lineHeight: 23,
    fontWeight: '900',
  },
  sectionHelper: {
    color: MUTED,
    fontSize: 12,
    lineHeight: 18,
    fontWeight: '700',
  },
  memorialOptionRow: {
    flexDirection: 'row',
    gap: 10,
  },
  memorialOption: {
    flex: 1,
    minHeight: 110,
    borderRadius: 16,
    paddingHorizontal: 13,
    paddingVertical: 13,
    backgroundColor: 'rgba(255, 253, 249, 0.62)',
    borderWidth: 1,
    borderColor: 'rgba(119, 91, 68, 0.10)',
    gap: 5,
  },
  memorialTitle: {
    color: '#4B3E36',
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '900',
  },
  memorialDescription: {
    color: '#7F7167',
    fontSize: 11,
    lineHeight: 16,
    fontWeight: '700',
  },
  fieldBlock: {
    gap: 7,
  },
  fieldLabelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  label: {
    color: '#645850',
    fontSize: 13,
    fontWeight: '800',
  },
  countText: {
    color: '#8E8177',
    fontSize: 12,
    fontWeight: '700',
  },
  input: {
    minHeight: 50,
    borderRadius: 15,
    backgroundColor: FIELD,
    borderWidth: 1,
    borderColor: 'rgba(119, 91, 68, 0.08)',
    paddingHorizontal: 14,
    color: TEXT,
    fontSize: 14,
    fontWeight: '700',
  },
  iconInputWrap: {
    minHeight: 50,
    borderRadius: 15,
    backgroundColor: FIELD,
    borderWidth: 1,
    borderColor: 'rgba(119, 91, 68, 0.08)',
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  iconInput: {
    flex: 1,
    color: TEXT,
    fontSize: 14,
    fontWeight: '700',
    paddingVertical: 12,
  },
  trailingUnit: {
    color: MUTED,
    fontSize: 13,
    fontWeight: '800',
  },
  inputHint: {
    color: '#8E8177',
    fontSize: 11,
    fontWeight: '600',
    lineHeight: 16,
  },
  row: {
    flexDirection: 'row',
    gap: 12,
  },
  col: {
    flex: 1,
    gap: 7,
  },
  segmentRow: {
    flexDirection: 'row',
    gap: 8,
  },
  segmentWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  segmentChip: {
    flex: 1,
    minHeight: 42,
    borderRadius: 13,
    backgroundColor: FIELD,
    borderWidth: 1,
    borderColor: 'rgba(119, 91, 68, 0.07)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 8,
  },
  segmentChipWide: {
    flexGrow: 0,
    flexBasis: '31%',
    minWidth: '31%',
  },
  segmentChipActive: {
    backgroundColor: 'rgba(109,106,248,0.12)',
    borderWidth: 1,
    borderColor: BORDER,
  },
  segmentChipText: {
    color: '#8E8177',
    fontSize: 12,
    fontWeight: '800',
  },
  segmentChipTextActive: {
    color: BRAND_DEEP,
  },
  quickChip: {
    minHeight: 36,
    borderRadius: 999,
    backgroundColor: FIELD,
    borderWidth: 1,
    borderColor: 'rgba(119, 91, 68, 0.07)',
    paddingHorizontal: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  quickChipActive: {
    backgroundColor: 'rgba(109,106,248,0.12)',
    borderWidth: 1,
    borderColor: BORDER,
  },
  quickChipText: {
    color: '#8E8177',
    fontSize: 12,
    fontWeight: '700',
  },
  quickChipTextActive: {
    color: BRAND_DEEP,
    fontWeight: '800',
  },
  tagInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  tagInput: {
    flex: 1,
  },
  inlineAddButton: {
    minWidth: 62,
    height: 50,
    borderRadius: 15,
    backgroundColor: 'rgba(109,106,248,0.12)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 12,
  },
  inlineAddButtonText: {
    color: BRAND_DEEP,
    fontSize: 13,
    fontWeight: '900',
  },
  pillRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  pill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: 'rgba(109,106,248,0.11)',
  },
  pillText: {
    color: BRAND_DEEP,
    fontSize: 12,
    fontWeight: '800',
  },
  pillX: {
    color: '#9D95FF',
    fontSize: 12,
    fontWeight: '900',
  },
  footerActions: {
    flexDirection: 'row',
    gap: 10,
  },
  primaryButton: {
    flex: 1,
    height: 52,
    borderRadius: 17,
    backgroundColor: BRAND,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: BRAND,
    shadowOpacity: 0.2,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 4,
  },
  primaryButtonText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '900',
  },
  secondaryButton: {
    flex: 0.72,
    height: 52,
    borderRadius: 17,
    backgroundColor: 'rgba(255, 253, 249, 0.82)',
    borderWidth: 1,
    borderColor: 'rgba(119, 91, 68, 0.10)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 10,
  },
  secondaryButtonText: {
    color: '#645850',
    fontSize: 13,
    fontWeight: '900',
  },
  actionZone: {
    paddingHorizontal: 16,
    paddingTop: spacing.md,
    borderTopWidth: 1,
    shadowColor: '#6E4D36',
    shadowOpacity: 0.1,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: -6 },
    elevation: 12,
  },
  actionRow: {
    width: '100%',
    flexDirection: 'row',
    gap: 10,
  },
  buttonDisabled: {
    opacity: 0.46,
  },
  modalBackdrop: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  successModalBackdrop: {
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: 8,
    backgroundColor: 'rgba(11,18,32,0.28)',
  },
  modalScrim: {
    ...StyleSheet.absoluteFill,
    backgroundColor: 'rgba(11,18,32,0.28)',
  },
  dateModalCard: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    paddingHorizontal: 20,
    paddingTop: 18,
    paddingBottom: 28,
    gap: 16,
  },
  dateModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  dateModalTitle: {
    color: TEXT,
    fontSize: 16,
    fontWeight: '800',
  },
  dateModalPreview: {
    color: BRAND_DEEP,
    fontSize: 14,
    fontWeight: '800',
  },
  datePickerRow: {
    flexDirection: 'row',
    gap: 10,
  },
  datePickerCol: {
    flex: 1.4,
    gap: 7,
  },
  datePickerMiniCol: {
    flex: 1,
    gap: 7,
  },
  datePickerLabel: {
    color: MUTED,
    fontSize: 12,
    fontWeight: '800',
  },
  datePickerInput: {
    minHeight: 48,
    borderRadius: 16,
    backgroundColor: FIELD,
    paddingHorizontal: 14,
    color: TEXT,
    fontSize: 14,
    fontWeight: '700',
  },
  dateModalActions: {
    flexDirection: 'row',
    gap: 10,
  },
  dateGhostButton: {
    flex: 1,
    height: 48,
    borderRadius: 16,
    backgroundColor: '#EEF1F8',
    alignItems: 'center',
    justifyContent: 'center',
  },
  dateGhostButtonText: {
    color: '#6C768A',
    fontSize: 13,
    fontWeight: '800',
  },
  dateConfirmButton: {
    flex: 1,
    height: 48,
    borderRadius: 16,
    backgroundColor: BRAND,
    alignItems: 'center',
    justifyContent: 'center',
  },
  dateConfirmButtonText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '900',
  },
  successModalCard: {
    marginHorizontal: 26,
    borderRadius: 28,
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 24,
    paddingTop: 18,
    paddingBottom: 24,
    alignItems: 'center',
    shadowColor: '#000000',
    shadowOpacity: 0.14,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 16 },
    elevation: 6,
  },
  successLogoWrap: {
    width: 200,
    height: 200,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: -8,
  },
  successLogo: {
    width: 200,
    height: 200,
  },
  successCopyWrap: {
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  successTitle: {
    color: TEXT,
    fontSize: 16,
    fontWeight: '900',
    textAlign: 'center',
    marginTop: -4,
  },
  successBody: {
    color: '#8A94A6',
    fontSize: 12,
    fontWeight: '700',
    textAlign: 'center',
    lineHeight: 18,
    marginTop: 4,
  },
  successPrimaryButton: {
    width: '100%',
    height: 50,
    borderRadius: 16,
    backgroundColor: BRAND,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 18,
    shadowColor: BRAND,
    shadowOpacity: 0.22,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 4,
  },
  successPrimaryButtonText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '900',
  },
});
