import { StyleSheet } from 'react-native';

import { spacing } from '../../app/theme/tokens/spacing';

const BRAND = '#6D6AF8';
const BRAND_DEEP = '#5753E6';
const TEXT = '#352B25';
const MUTED_TEXT = '#786B61';
const INPUT_SURFACE = 'rgba(255, 253, 249, 0.78)';
const GLASS_SURFACE = 'rgba(255, 252, 246, 0.70)';

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#FBF3E7',
  },
  backgroundImage: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    width: '100%',
    height: '100%',
  },
  backgroundWarmth: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    backgroundColor: 'rgba(255, 248, 237, 0.06)',
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 18,
    paddingTop: 4,
    paddingBottom: 28,
    gap: 16,
  },
  header: {
    minHeight: 56,
    paddingHorizontal: 18,
    paddingTop: 8,
    paddingBottom: 8,
    marginTop: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    zIndex: 4,
  },
  headerSideSlot: {
    width: 40,
    minHeight: 40,
    justifyContent: 'center',
    alignItems: 'flex-start',
  },
  headerSideSlotRight: {
    alignItems: 'flex-end',
  },
  backButton: {
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 20,
    backgroundColor: 'rgba(255, 252, 247, 0.54)',
  },
  headerTitle: {
    flex: 1,
    textAlign: 'center',
    color: '#273241',
    fontWeight: '900',
  },
  avatarSection: {
    marginTop: 6,
    marginBottom: 8,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
  },
  avatarHalo: {
    width: 156,
    height: 156,
    borderRadius: 999,
    padding: 5,
    alignItems: 'center',
    justifyContent: 'center',
    shadowOpacity: 0.24,
    shadowRadius: 22,
    shadowOffset: { width: 0, height: 8 },
    elevation: 7,
  },
  avatarWrap: {
    width: 146,
    height: 146,
    borderRadius: 999,
    overflow: 'visible',
    backgroundColor: '#E9D7C1',
    borderWidth: 3,
    shadowColor: '#6E4D36',
    shadowOpacity: 0.12,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 6 },
    elevation: 4,
  },
  avatarImage: {
    width: '100%',
    height: '100%',
    borderRadius: 999,
  },
  avatarFallback: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F1E7D8',
    borderRadius: 999,
  },
  avatarCameraBtn: {
    position: 'absolute',
    bottom: 8,
    right: 3,
    width: 34,
    height: 34,
    borderRadius: 999,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: '#FFFFFF',
    shadowColor: '#000000',
    shadowOpacity: 0.14,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 6,
    zIndex: 10,
  },
  profileName: {
    marginTop: 8,
    fontSize: 24,
    lineHeight: 30,
    fontWeight: '900',
    textAlign: 'center',
  },
  profileMeta: {
    fontWeight: '800',
    textAlign: 'center',
  },
  profileMetaMuted: {
    color: '#8C7F75',
    fontWeight: '700',
    textAlign: 'center',
  },
  sectionGlass: {
    borderRadius: 22,
    paddingHorizontal: 17,
    paddingVertical: 17,
    gap: 14,
    backgroundColor: GLASS_SURFACE,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.72)',
    overflow: 'hidden',
  },
  sectionHeader: {
    gap: 3,
  },
  sectionTitle: {
    color: TEXT,
    fontSize: 18,
    lineHeight: 23,
    fontWeight: '900',
  },
  sectionHelper: {
    color: MUTED_TEXT,
    fontSize: 12,
    lineHeight: 18,
    fontWeight: '700',
  },
  formSection: {
    gap: 16,
  },
  fieldBlock: {
    gap: 7,
  },
  label: {
    color: '#645850',
    fontSize: 13,
    fontWeight: '800',
  },
  input: {
    minHeight: 50,
    borderRadius: 15,
    backgroundColor: INPUT_SURFACE,
    borderWidth: 1,
    borderColor: 'rgba(119, 91, 68, 0.08)',
    paddingHorizontal: 14,
    color: TEXT,
    fontWeight: '700',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  readonlyInputText: {
    flex: 1,
    color: TEXT,
    fontWeight: '700',
    paddingVertical: 0,
    paddingHorizontal: 0,
  },
  inputDisabled: {
    opacity: 0.62,
  },
  inputHint: {
    color: '#8E8177',
    fontSize: 11,
    lineHeight: 16,
    fontWeight: '700',
  },
  row: {
    flexDirection: 'row',
    gap: 10,
  },
  col: {
    flex: 1,
    gap: 7,
  },
  searchInputWrap: {
    minHeight: 50,
    borderRadius: 15,
    backgroundColor: INPUT_SURFACE,
    borderWidth: 1,
    borderColor: 'rgba(119, 91, 68, 0.08)',
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  searchInput: {
    flex: 1,
    color: TEXT,
    fontWeight: '700',
  },
  weightButton: {
    minHeight: 48,
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  segmentRow: {
    flexDirection: 'row',
    gap: 8,
  },
  segmentWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  segmentChip: {
    flex: 1,
    minHeight: 40,
    borderRadius: 13,
    backgroundColor: 'rgba(255, 253, 249, 0.68)',
    borderWidth: 1,
    borderColor: 'rgba(119, 91, 68, 0.07)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  segmentChipWide: {
    flexGrow: 0,
    flexBasis: '31%',
    minWidth: '31%',
    paddingHorizontal: 8,
  },
  segmentChipActive: {
    borderColor: 'rgba(109, 106, 248, 0.20)',
  },
  segmentChipText: {
    color: '#8E8177',
    fontWeight: '800',
  },
  segmentChipTextActive: {
    color: BRAND_DEEP,
    fontWeight: '900',
  },
  quickChip: {
    minHeight: 34,
    borderRadius: 999,
    backgroundColor: 'rgba(255, 253, 249, 0.68)',
    borderWidth: 1,
    borderColor: 'rgba(119, 91, 68, 0.07)',
    paddingHorizontal: 11,
    alignItems: 'center',
    justifyContent: 'center',
  },
  quickChipActive: {
    borderColor: 'rgba(109, 106, 248, 0.20)',
  },
  quickChipText: {
    color: '#8E8177',
    fontWeight: '800',
  },
  quickChipTextActive: {
    color: BRAND_DEEP,
    fontWeight: '900',
  },
  memorialOptionRow: {
    flexDirection: 'row',
    gap: 10,
  },
  memorialOption: {
    flex: 1,
    minHeight: 112,
    borderRadius: 16,
    paddingHorizontal: 13,
    paddingVertical: 13,
    backgroundColor: 'rgba(255, 253, 249, 0.62)',
    borderWidth: 1,
    borderColor: 'rgba(119, 91, 68, 0.10)',
    gap: 5,
  },
  memorialTitle: {
    color: '#4B3E36',
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '900',
  },
  memorialDescription: {
    color: '#7F7167',
    fontSize: 11,
    lineHeight: 16,
    fontWeight: '700',
  },
  inlineLabel: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
  },
  labelInlineText: {
    color: '#645850',
    fontSize: 13,
    fontWeight: '800',
  },
  multilineInput: {
    minHeight: 58,
    maxHeight: 108,
    paddingTop: 11,
    paddingBottom: 11,
    textAlignVertical: 'top',
  },
  tagRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  tagChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    borderRadius: 999,
    paddingHorizontal: 11,
    paddingVertical: 8,
  },
  tagChipText: {
    color: BRAND_DEEP,
    fontWeight: '900',
  },
  tagChipX: {
    color: '#9F8CFB',
    fontWeight: '900',
  },
  tagInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  tagInput: {
    flex: 1,
    minHeight: 44,
    borderRadius: 14,
    backgroundColor: INPUT_SURFACE,
    borderWidth: 1,
    borderColor: 'rgba(119, 91, 68, 0.08)',
    paddingHorizontal: 13,
    color: TEXT,
    fontWeight: '700',
  },
  tagAddButton: {
    height: 44,
    borderRadius: 14,
    paddingHorizontal: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  tagAddButtonText: {
    color: BRAND_DEEP,
    fontWeight: '900',
  },
  tagCount: {
    color: '#8E8177',
    fontWeight: '800',
  },
  recommendWrap: {
    gap: 9,
  },
  recommendHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  recommendLabel: {
    color: '#7F7167',
    fontWeight: '800',
  },
  recommendRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    columnGap: 5,
    rowGap: 7,
  },
  recommendChip: {
    width: '18.5%',
    minHeight: 34,
    borderRadius: 999,
    paddingHorizontal: 4,
    paddingVertical: 6,
    alignItems: 'center',
    justifyContent: 'center',
  },
  recommendChipBlue: {
    backgroundColor: 'rgba(218, 235, 255, 0.72)',
  },
  recommendChipOrange: {
    backgroundColor: 'rgba(255, 226, 196, 0.74)',
  },
  recommendChipGreen: {
    backgroundColor: 'rgba(217, 242, 225, 0.74)',
  },
  recommendChipPink: {
    backgroundColor: 'rgba(255, 220, 235, 0.72)',
  },
  recommendChipPurple: {
    backgroundColor: 'rgba(229, 220, 255, 0.72)',
  },
  recommendChipText: {
    color: '#655178',
    fontSize: 11,
    lineHeight: 15,
    fontWeight: '900',
    textAlign: 'center',
  },
  primaryButton: {
    minHeight: 54,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: BRAND,
    shadowColor: BRAND,
    shadowOpacity: 0.22,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 7 },
    elevation: 5,
  },
  primaryButtonDisabled: {
    opacity: 0.6,
  },
  primaryButtonText: {
    color: '#FFFFFF',
    fontWeight: '900',
  },
  stickyActionSection: {
    paddingHorizontal: 16,
    paddingTop: spacing.md,
    backgroundColor: 'rgba(255, 249, 239, 0.92)',
    borderTopWidth: 1,
    borderTopColor: 'rgba(255, 255, 255, 0.78)',
    shadowColor: '#6E4D36',
    shadowOpacity: 0.1,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: -6 },
    elevation: 12,
  },
  stickyActionInner: {
    width: '100%',
  },
  centerFallback: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
    gap: 16,
  },
  fallbackTitle: {
    color: TEXT,
    fontWeight: '800',
  },
});
