import { StyleSheet } from 'react-native';

const BRAND = '#6D6AF8';
const BRAND_DEEP = '#5753E6';
const TEXT = '#0B1220';
const MUTED = '#94A0B4';

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#F7F8FC',
    paddingHorizontal: 22,
    paddingTop: 40,
    paddingBottom: 32,
    justifyContent: 'space-between',
  },
  hero: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: 0,
  },
  checkCard: {
    width: 106,
    height: 106,
    borderRadius: 30,
    backgroundColor: BRAND,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: BRAND_DEEP,
    shadowOpacity: 0.24,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 14 },
    elevation: 6,
  },
  checkCircle: {
    width: 48,
    height: 48,
    borderRadius: 999,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  title: {
    marginTop: 34,
    color: TEXT,
    fontWeight: '900',
    textAlign: 'center',
  },
  body: {
    marginTop: 8,
    color: MUTED,
    textAlign: 'center',
  },
  meta: {
    marginTop: 10,
    color: BRAND_DEEP,
    fontWeight: '800',
    textAlign: 'center',
  },
  primaryButton: {
    height: 56,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: BRAND,
    shadowColor: BRAND,
    shadowOpacity: 0.2,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 10 },
    elevation: 4,
  },
  primaryButtonText: {
    color: '#FFFFFF',
    fontWeight: '900',
  },
  confettiOne: {
    position: 'absolute',
    top: 160,
    left: 74,
    width: 10,
    height: 10,
    borderRadius: 2,
    backgroundColor: 'rgba(109,106,248,0.18)',
    transform: [{ rotate: '12deg' }],
  },
  confettiTwo: {
    position: 'absolute',
    top: 192,
    right: 72,
    width: 8,
    height: 8,
    borderRadius: 2,
    backgroundColor: 'rgba(245,194,66,0.6)',
    transform: [{ rotate: '18deg' }],
  },
  confettiThree: {
    position: 'absolute',
    top: 276,
    left: 40,
    width: 7,
    height: 7,
    borderRadius: 2,
    backgroundColor: 'rgba(255,193,203,0.5)',
    transform: [{ rotate: '20deg' }],
  },
  confettiFour: {
    position: 'absolute',
    top: 320,
    right: 38,
    width: 8,
    height: 8,
    borderRadius: 2,
    backgroundColor: 'rgba(109,106,248,0.14)',
    transform: [{ rotate: '-18deg' }],
  },
  confettiFive: {
    position: 'absolute',
    top: 236,
    left: 188,
    width: 12,
    height: 12,
    borderRadius: 3,
    backgroundColor: 'rgba(109,106,248,0.1)',
    transform: [{ rotate: '8deg' }],
  },
});
