import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  button: {
    minHeight: 48,
    minWidth: 48,
    maxWidth: '100%',
    flexShrink: 1,
    paddingHorizontal: 0,
    paddingVertical: 4,
    borderRadius: 0,
    borderWidth: 0,
    backgroundColor: 'transparent',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
  },
  compactButton: {
    minHeight: 48,
    minWidth: 48,
    maxWidth: '100%',
    flexShrink: 1,
    paddingHorizontal: 0,
    paddingVertical: 4,
    borderRadius: 0,
    borderWidth: 0,
    backgroundColor: 'transparent',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
  },
  text: {
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '500',
    letterSpacing: 0,
    textAlign: 'center',
    flexShrink: 1,
  },
  pressed: {
    opacity: 0.9,
  },
});
