import { StyleSheet } from 'react-native';

const TEXT = '#1B2435';
const SUB = '#8B96A9';
const BRAND = '#6D6AF8';

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  keyboardView: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
    paddingHorizontal: 20,
    paddingTop: 40,
    paddingBottom: 28,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 30,
  },
  headerBackButton: {
    width: 36,
    height: 36,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: {
    color: TEXT,
    fontSize: 16,
    fontWeight: '900',
  },
  headerSpacer: {
    width: 36,
    height: 36,
  },
  heroCopy: {
    marginBottom: 26,
  },
  heroTitle: {
    color: TEXT,
    fontSize: 16,
    lineHeight: 24,
    fontWeight: '900',
    marginBottom: 8,
  },
  heroBody: {
    color: SUB,
    fontSize: 12,
    lineHeight: 18,
    fontWeight: '700',
  },
  fieldBlock: {
    marginBottom: 14,
  },
  label: {
    color: TEXT,
    fontSize: 12,
    fontWeight: '800',
    marginBottom: 8,
  },
  inputRow: {
    height: 56,
    borderRadius: 16,
    backgroundColor: '#F7F9FC',
    borderWidth: 1,
    borderColor: '#EDF1F7',
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
  },
  input: {
    flex: 1,
    color: TEXT,
    fontSize: 14,
    fontWeight: '700',
  },
  inputAccessory: {
    marginLeft: 10,
  },
  errorText: {
    color: '#E34F5F',
    fontSize: 12,
    lineHeight: 18,
    fontWeight: '700',
    marginTop: -4,
    marginBottom: 8,
  },
  termsRow: {
    marginTop: 6,
    marginBottom: 18,
    minHeight: 48,
    borderRadius: 16,
    backgroundColor: '#FBFCFE',
    borderWidth: 1,
    borderColor: '#EEF2F7',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  checkbox: {
    width: 22,
    height: 22,
    borderRadius: 6,
    borderWidth: 1.5,
    borderColor: '#D6DEEA',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFFFFF',
    marginRight: 10,
  },
  checkboxChecked: {
    backgroundColor: BRAND,
    borderColor: BRAND,
  },
  termsText: {
    flex: 1,
    color: '#6B778C',
    fontSize: 12,
    lineHeight: 18,
    fontWeight: '700',
  },
  termsLink: {
    color: BRAND,
    textDecorationLine: 'underline',
    fontWeight: '900',
  },
  termsMeta: {
    marginTop: -8,
    marginBottom: 18,
    color: '#9CA3AF',
    fontSize: 11,
    fontWeight: '700',
  },
  primaryButton: {
    height: 56,
    borderRadius: 18,
    backgroundColor: BRAND,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: BRAND,
    shadowOpacity: 0.22,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 5,
  },
  primaryButtonDisabled: {
    opacity: 0.45,
  },
  primaryButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '900',
  },
  socialLead: {
    textAlign: 'center',
    color: '#C0C7D4',
    fontSize: 12,
    lineHeight: 18,
    fontWeight: '700',
    marginVertical: 18,
  },
  socialButton: {
    height: 56,
    borderRadius: 16,
    borderWidth: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  socialBadge: {
    position: 'absolute',
    left: 18,
  },
  socialButtonText: {
    fontSize: 15,
    fontWeight: '900',
  },
  kakaoBadge: {
    width: 18,
    height: 15,
    borderRadius: 6,
    backgroundColor: '#3A2800',
  },
  googleBadge: {
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  googleBadgeText: {
    color: '#4285F4',
    fontSize: 12,
    fontWeight: '900',
  },
  signInRow: {
    marginTop: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  signInHint: {
    color: '#B9C1CE',
    fontSize: 12,
    fontWeight: '700',
  },
  signInLink: {
    color: BRAND,
    fontSize: 12,
    fontWeight: '900',
  },
});
