import { StyleSheet } from 'react-native';
import { typography } from '../../app/theme/tokens/typography';

const TEXT = '#1B2435';
const SUB = '#8B96A9';
const BRAND = '#6D6AF8';

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  seasonalBackground: {
    flex: 1,
  },
  seasonalBackgroundWash: {
    ...StyleSheet.absoluteFill,
  },
  seasonalSafeArea: {
    flex: 1,
    backgroundColor: 'transparent',
  },
  keyboardView: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
    paddingHorizontal: 20,
    paddingTop: 40,
    paddingBottom: 28,
  },
  seasonalScrollContent: {
    flexGrow: 1,
    paddingHorizontal: 26,
    paddingBottom: 30,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 30,
  },
  seasonalHeaderRow: {
    justifyContent: 'flex-start',
    marginBottom: 0,
    minHeight: 44,
  },
  headerBackButton: {
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
  },
  seasonalHeaderBackButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255, 252, 248, 0.82)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.78)',
  },
  headerTitle: {
    color: TEXT,
    ...typography.role.titleSm,
    fontWeight: '800',
  },
  headerSpacer: {
    width: 44,
    height: 44,
  },
  heroCopy: {
    marginBottom: 26,
  },
  seasonalHeroSpacer: {
    width: '100%',
  },
  accessibilityHeading: {
    position: 'absolute',
    width: 1,
    height: 1,
    opacity: 0,
  },
  heroTitle: {
    color: TEXT,
    ...typography.role.titleLg,
    fontWeight: '800',
    marginBottom: 8,
  },
  heroBody: {
    color: SUB,
    ...typography.role.bodySm,
    fontWeight: '700',
  },
  fieldBlock: {
    marginBottom: 14,
  },
  seasonalFieldBlock: {
    marginBottom: 9,
  },
  label: {
    color: TEXT,
    ...typography.role.helper,
    fontWeight: '700',
    marginBottom: 8,
  },
  inputRow: {
    minHeight: 56,
    borderRadius: 16,
    backgroundColor: '#F7F9FC',
    borderWidth: 1,
    borderColor: '#EDF1F7',
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
  },
  seasonalInputRow: {
    minHeight: 48,
    borderRadius: 15,
    paddingHorizontal: 14,
    shadowOpacity: 0.09,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  input: {
    flex: 1,
    color: TEXT,
    ...typography.role.body,
    fontWeight: '700',
  },
  seasonalInput: {
    fontSize: 14,
    lineHeight: 19,
    fontWeight: '600',
    paddingVertical: 0,
  },
  inputAccessory: {
    marginLeft: 10,
  },
  errorText: {
    color: '#E34F5F',
    ...typography.role.helper,
    fontWeight: '700',
    marginTop: -4,
    marginBottom: 8,
  },
  seasonalErrorText: {
    color: '#FFFFFF',
    fontSize: 11,
    lineHeight: 16,
    marginTop: -2,
    marginBottom: 6,
  },
  termsRow: {
    marginTop: 6,
    marginBottom: 18,
  },
  termsCard: {
    marginTop: 6,
    marginBottom: 10,
    borderRadius: 20,
    backgroundColor: '#FBFCFE',
    borderWidth: 1,
    borderColor: '#EEF2F7',
    paddingHorizontal: 14,
    paddingVertical: 14,
    gap: 12,
  },
  seasonalTermsCard: {
    marginTop: 5,
    marginBottom: 8,
    borderRadius: 17,
    paddingHorizontal: 11,
    paddingVertical: 11,
    gap: 8,
    shadowColor: '#8E4D28',
    shadowOpacity: 0.08,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 5 },
    elevation: 2,
  },
  termsCardHeader: {
    flexDirection: 'row',
    gap: 12,
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  seasonalTermsCardHeader: {
    gap: 8,
  },
  termsCardHeaderCopy: {
    flex: 1,
    gap: 6,
  },
  seasonalTermsCardHeaderCopy: {
    gap: 3,
  },
  termsCardTitle: {
    color: TEXT,
    ...typography.role.body,
    fontWeight: '800',
  },
  seasonalTermsCardTitle: {
    fontSize: 14,
    lineHeight: 19,
  },
  termsCardBody: {
    color: '#6B778C',
    ...typography.role.helper,
    fontWeight: '700',
  },
  seasonalTermsCardBody: {
    fontSize: 11,
    lineHeight: 16,
  },
  allAgreeButton: {
    minHeight: 48,
    minWidth: 124,
    paddingHorizontal: 12,
    borderRadius: 14,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E3E8F2',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  seasonalAllAgreeButton: {
    minHeight: 42,
    minWidth: 112,
    paddingHorizontal: 9,
    borderRadius: 13,
  },
  allAgreeLabel: {
    color: TEXT,
    ...typography.role.tab,
    fontWeight: '900',
    marginLeft: 8,
  },
  seasonalAllAgreeLabel: {
    fontSize: 12,
    lineHeight: 16,
    marginLeft: 5,
  },
  termsDivider: {
    height: 1,
    backgroundColor: '#EEF2F7',
  },
  consentCardRow: {
    borderRadius: 16,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#EEF2F7',
    paddingHorizontal: 12,
    paddingVertical: 12,
    gap: 10,
  },
  seasonalConsentCardRow: {
    borderRadius: 13,
    paddingHorizontal: 9,
    paddingVertical: 8,
    gap: 7,
  },
  consentHeaderRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
  },
  seasonalConsentHeaderRow: {
    gap: 7,
  },
  consentToggle: {
    flex: 1,
    minHeight: 44,
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  disclosureButton: {
    width: 44,
    height: 44,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  seasonalDisclosureButton: {
    width: 40,
    height: 40,
    borderRadius: 11,
  },
  consentCopy: {
    flex: 1,
    gap: 4,
  },
  seasonalConsentCopy: {
    gap: 2,
  },
  consentTitleRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: 8,
  },
  consentBadge: {
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  seasonalConsentBadge: {
    paddingHorizontal: 7,
    paddingVertical: 2,
  },
  requiredBadge: {
    backgroundColor: '#FDECEC',
  },
  optionalBadge: {
    backgroundColor: '#EEF2FF',
  },
  consentBadgeText: {
    ...typography.role.caption,
    fontWeight: '900',
  },
  requiredBadgeText: {
    color: '#C34D5C',
  },
  optionalBadgeText: {
    color: '#4F63D9',
  },
  consentTitle: {
    color: TEXT,
    ...typography.role.bodySm,
    fontWeight: '900',
  },
  seasonalConsentTitle: {
    fontSize: 12,
    lineHeight: 17,
  },
  checkbox: {
    width: 22,
    height: 22,
    borderRadius: 6,
    borderWidth: 1.5,
    borderColor: '#D6DEEA',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFFFFF',
    marginRight: 10,
    marginTop: 1,
  },
  seasonalCheckbox: {
    width: 20,
    height: 20,
    borderRadius: 6,
    marginRight: 8,
  },
  checkboxChecked: {
    backgroundColor: BRAND,
    borderColor: BRAND,
  },
  checkboxDisabled: {
    opacity: 0.55,
  },
  termsText: {
    flex: 1,
    color: '#6B778C',
    ...typography.role.helper,
    fontWeight: '700',
  },
  seasonalTermsText: {
    fontSize: 10.5,
    lineHeight: 15,
  },
  consentExpandedBox: {
    borderRadius: 14,
    backgroundColor: '#F8FAFD',
    borderWidth: 1,
    borderColor: '#E8EDF6',
    paddingHorizontal: 12,
    paddingVertical: 12,
    gap: 8,
  },
  seasonalConsentExpandedBox: {
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 9,
    gap: 6,
  },
  expandedMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  expandedTitle: {
    flex: 1,
    color: TEXT,
    ...typography.role.helper,
    fontWeight: '900',
  },
  statusChip: {
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 4,
    backgroundColor: '#EEF2FF',
  },
  statusChipText: {
    color: '#4F63D9',
    ...typography.role.caption,
    fontWeight: '900',
  },
  expandedSummary: {
    color: TEXT,
    ...typography.role.helper,
    fontWeight: '800',
  },
  expandedDescription: {
    color: '#6B778C',
    ...typography.role.helper,
    fontWeight: '700',
  },
  documentButton: {
    minHeight: 42,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#DCE3F0',
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 12,
  },
  documentButtonText: {
    color: BRAND,
    ...typography.role.tab,
    fontWeight: '900',
  },
  termsMeta: {
    marginTop: -2,
    marginBottom: 18,
    color: '#9CA3AF',
    ...typography.role.helper,
    fontWeight: '700',
  },
  seasonalTermsMeta: {
    marginTop: -1,
    marginBottom: 11,
    fontSize: 10.5,
    lineHeight: 15,
  },
  legalNoticeBox: {
    marginTop: -6,
    marginBottom: 18,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#E7ECF5',
    backgroundColor: '#F8FAFD',
    paddingHorizontal: 14,
    paddingVertical: 12,
    gap: 6,
  },
  legalNoticeTitle: {
    color: TEXT,
    ...typography.role.helper,
    fontWeight: '900',
  },
  legalNoticeBody: {
    color: '#718096',
    ...typography.role.helper,
    fontWeight: '700',
  },
  primaryButton: {
    minHeight: 56,
    borderRadius: 18,
    backgroundColor: BRAND,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: BRAND,
    shadowOpacity: 0.22,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 5,
  },
  seasonalPrimaryButton: {
    minHeight: 50,
    borderRadius: 16,
    shadowOpacity: 0.2,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 4,
  },
  primaryButtonDisabled: {
    opacity: 0.45,
  },
  primaryButtonText: {
    color: '#FFFFFF',
    ...typography.role.button,
    fontWeight: '900',
  },
  seasonalPrimaryButtonText: {
    fontSize: 15,
    lineHeight: 20,
  },
  signInRow: {
    marginTop: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  seasonalSignInRow: {
    marginTop: 9,
  },
  signInHint: {
    color: '#B9C1CE',
    ...typography.role.helper,
    fontWeight: '700',
  },
  seasonalSignInText: {
    color: '#FFFFFF',
    fontSize: 14,
    lineHeight: 20,
  },
  signInLink: {
    color: BRAND,
    ...typography.role.helper,
    fontWeight: '900',
  },
});
