import { StyleSheet } from 'react-native';
import { typography } from '../../app/theme/tokens/typography';

const TEXT = '#1B2435';

const BRAND = '#6D6AF8';

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  successBackdrop: {
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: 24,
  },
  successScrim: {
    ...StyleSheet.absoluteFillObject,
  },
  successCard: {
    borderRadius: 28,
    borderWidth: 1,
    paddingHorizontal: 24,
    paddingTop: 26,
    paddingBottom: 24,
    alignItems: 'center',
    shadowColor: '#171B25',
    shadowOpacity: 0.24,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 14 },
    elevation: 12,
  },
  successHalo: {
    width: 92,
    height: 92,
    borderRadius: 46,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
  },
  successIcon: {
    width: 62,
    height: 62,
    borderRadius: 31,
    alignItems: 'center',
    justifyContent: 'center',
  },
  successEyebrow: {
    marginTop: 18,
    ...typography.role.caption,
    fontWeight: '900',
    letterSpacing: 1.6,
  },
  successTitle: {
    marginTop: 10,
    textAlign: 'center',
    ...typography.role.titleLg,
    fontWeight: '800',
  },
  successBody: {
    marginTop: 10,
    textAlign: 'center',
    ...typography.role.body,
    fontWeight: '600',
  },
  successButton: {
    width: '100%',
    marginTop: 24,
    minHeight: 54,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  successButtonText: {
    color: '#FFF8EE',
    ...typography.role.button,
    fontWeight: '900',
  },
  keyboardView: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
    paddingHorizontal: 28,
    paddingTop: 36,
    paddingBottom: 28,
  },
  hero: {
    alignItems: 'center',
    marginTop: 36,
    marginBottom: 38,
  },
  heroLogoWrap: {
    width: 82,
    height: 82,
    borderRadius: 28,
    alignItems: 'center',
    justifyContent: 'center',
  },
  heroLogo: {
    width: 118,
    height: 118,
  },
  heroBody: {
    marginTop: 14,
    maxWidth: 248,
    ...typography.role.body,
    fontWeight: '600',
    color: '#000000',
    textAlign: 'center',
  },
  fieldBlock: {
    marginBottom: 16,
  },
  fieldLabel: {
    display: 'none',
  },
  inputRow: {
    minHeight: 56,
    borderRadius: 16,
    backgroundColor: '#F7F9FC',
    borderWidth: 1,
    borderColor: '#EDF1F7',
    paddingHorizontal: 18,
    flexDirection: 'row',
    alignItems: 'center',
  },
  input: {
    flex: 1,
    color: TEXT,
    ...typography.role.body,
    fontWeight: '700',
  },
  inputAccessory: {
    marginLeft: 12,
  },
  primaryButton: {
    marginTop: 10,
    minHeight: 56,
    borderRadius: 18,
    backgroundColor: BRAND,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: BRAND,
    shadowOpacity: 0.22,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 5,
  },
  primaryButtonDisabled: {
    opacity: 0.45,
  },
  primaryButtonText: {
    color: '#FFFFFF',
    ...typography.role.button,
    fontWeight: '900',
  },
  inlineLinks: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 10,
    marginTop: 18,
  },
  inlineLinkText: {
    color: '#7D8798',
    ...typography.role.helper,
    fontWeight: '800',
  },
  inlineDivider: {
    color: '#C8D0DC',
    ...typography.role.helper,
    fontWeight: '700',
  },
  socialSection: {
    marginTop: 58,
    marginBottom: 18,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  socialDivider: {
    flex: 1,
    height: 1,
    backgroundColor: '#E7ECF4',
  },
  socialSectionTitle: {
    color: '#AAB3C1',
    ...typography.role.helper,
    fontWeight: '800',
  },
  socialButton: {
    minHeight: 56,
    borderRadius: 16,
    borderWidth: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  socialBadge: {
    position: 'absolute',
    left: 18,
  },
  socialButtonText: {
    ...typography.role.button,
    fontWeight: '900',
  },
  kakaoBadge: {
    width: 20,
    height: 20,
    borderRadius: 6,
    backgroundColor: '#FEE500',
    alignItems: 'center',
    justifyContent: 'center',
  },
  kakaoBubble: {
    width: 10,
    height: 8,
    borderRadius: 3,
    backgroundColor: '#3C1E1E',
    position: 'relative',
  },
  kakaoBubbleTail: {
    position: 'absolute',
    left: 2,
    bottom: -2,
    width: 4,
    height: 4,
    borderRadius: 1,
    backgroundColor: '#3C1E1E',
    transform: [{ rotate: '45deg' }],
  },
  googleBadge: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F2',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
