import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: '#FFFFFF' },
  scrollContent: { flexGrow: 1 },
  hero: { alignItems: 'center', overflow: 'hidden', marginTop: -8 },
  statusBarBackground: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    backgroundColor: '#FFFFFF',
  },
  actions: {
    width: '100%',
    maxWidth: 440,
    alignSelf: 'center',
    paddingHorizontal: 24,
    paddingTop: 8,
    paddingBottom: 12,
    justifyContent: 'flex-start',
    gap: 10,
    backgroundColor: '#FFFFFF',
  },
  socialButton: {
    minHeight: 52,
    borderRadius: 8,
    borderWidth: 1,
    paddingHorizontal: 16,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  kakaoButton: { backgroundColor: '#FEE500', borderColor: '#FEE500' },
  googleButton: { backgroundColor: '#FFFFFF', borderColor: '#747775' },
  disabledButton: { opacity: 0.55 },
  providerIcon: { width: 20, height: 20 },
  buttonLeading: {
    flex: 1,
    alignItems: 'flex-start',
    justifyContent: 'center',
    minWidth: 0,
  },
  buttonCopy: { flex: 3, alignItems: 'center', minWidth: 0 },
  buttonLabel: {
    fontSize: 16,
    lineHeight: 22,
    fontWeight: '500',
    color: '#1F1F1F',
    textAlign: 'center',
    includeFontPadding: false,
    letterSpacing: 0,
  },
  kakaoLabel: { color: 'rgba(0, 0, 0, 0.85)' },
  recentLabel: {
    color: '#454545',
    fontSize: 11,
    lineHeight: 16,
    textAlign: 'right',
    includeFontPadding: false,
  },
  buttonTrailingSpace: {
    flex: 1,
    alignItems: 'flex-end',
    justifyContent: 'center',
    minWidth: 0,
  },
  legal: { alignItems: 'center', gap: 0 },
  legalLinks: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    columnGap: 12,
  },
  legalLink: { minHeight: 48, justifyContent: 'center' },
  legalLinkText: {
    color: '#41434A',
    fontSize: 12,
    lineHeight: 18,
    textDecorationLine: 'underline',
  },
  unavailableText: { color: '#41434A', textAlign: 'center' },
});
