import type { NuriIconName } from './NuriIcon';

export const NURI_FUNCTION_ICONS = {
  walk: 'walk',
  meal: 'meal',
  health: 'health',
  grooming: 'grooming',
  diary: 'diary',
  calendar: 'calendar',
  timeline: 'timeline',
} as const satisfies Record<string, NuriIconName>;

const MATERIAL_NAMES: Readonly<Record<string, NuriIconName>> = {
  'account-search-outline': 'user-search',
  'alarm-light-outline': 'bell',
  'bullhorn-outline': 'megaphone',
  walk: 'walk',
  'silverware-fork-knife': 'meal',
  'heart-pulse': 'health',
  heart: 'heart',
  'heart-outline': 'heart',
  'content-cut': 'grooming',
  'notebook-outline': 'diary',
  notebook: 'diary',
  calendar: 'calendar',
  'calendar-blank': 'calendar',
  'calendar-blank-outline': 'calendar',
  'calendar-month-outline': 'calendar',
  'calendar-clock-outline': 'calendar-clock',
  'calendar-alert-outline': 'calendar-alert',
  'cards-outline': 'layers',
  'check-circle-outline': 'check-circle',
  'content-save-outline': 'save',
  cookie: 'cookie',
  'cookie-outline': 'cookie',
  curtains: 'curtains',
  dots: 'more-horizontal',
  'dots-grid': 'grid',
  'dots-horizontal-circle-outline': 'more-horizontal',
  'flag-checkered': 'flag',
  flower: 'flower',
  'food-drumstick-outline': 'treat',
  'gesture-tap-hold': 'touch',
  'hand-front-right-outline': 'hand',
  'hand-heart-outline': 'hand-heart',
  'home-heart': 'home',
  image: 'image',
  'image-outline': 'image',
  'layers-outline': 'layers',
  leaf: 'leaf',
  'leaf-maple': 'leaf',
  'map-marker-path': 'walk',
  'map-outline': 'map',
  'medal-outline': 'award',
  'medical-bag': 'medical-bag',
  meditation: 'meditation',
  'message-processing': 'community',
  needle: 'needle',
  'party-popper': 'party',
  'pause-circle-outline': 'pause-circle',
  paw: 'pet',
  pill: 'pill',
  pin: 'pin',
  'power-sleep': 'sleep',
  'school-outline': 'school',
  'shopping-outline': 'shopping',
  shower: 'shower',
  snowflake: 'snowflake',
  star: 'star',
  'star-circle-outline': 'star',
  'star-four-points': 'sparkles',
  stethoscope: 'stethoscope',
  'tennis-ball': 'ball',
  'timer-sand': 'sand-timer',
  'toy-brick-outline': 'toy-brick',
  'weather-night': 'moon',
};

const FEATHER_NAMES: Readonly<Record<string, NuriIconName>> = {
  activity: 'activity',
  'alert-circle': 'warning-circle',
  'alert-octagon': 'warning-octagon',
  'alert-triangle': 'warning',
  award: 'award',
  'bar-chart': 'chart',
  'bar-chart-2': 'chart',
  bell: 'bell',
  'bell-off': 'bell-off',
  'book-open': 'diary',
  calendar: 'calendar',
  camera: 'camera',
  check: 'check',
  'check-circle': 'check-circle',
  'check-square': 'check-square',
  circle: 'circle',
  clipboard: 'timeline',
  clock: 'clock',
  cloud: 'cloud',
  coffee: 'meal',
  crosshair: 'target',
  droplet: 'drop',
  edit: 'pen',
  'edit-2': 'pen',
  'edit-3': 'pen',
  eye: 'eye',
  'eye-off': 'eye-off',
  'file-text': 'file',
  flag: 'flag',
  hash: 'hashtag',
  heart: 'heart',
  home: 'home',
  image: 'image',
  info: 'info',
  loader: 'loader',
  lock: 'lock',
  mail: 'letter',
  map: 'map',
  'map-pin': 'pin',
  menu: 'menu',
  'message-circle': 'community',
  minus: 'minus',
  'more-horizontal': 'more-horizontal',
  'more-vertical': 'more-vertical',
  pause: 'pause',
  phone: 'phone',
  plus: 'plus',
  'plus-square': 'plus-square',
  save: 'save',
  search: 'search',
  send: 'send',
  settings: 'settings',
  shield: 'shield',
  'shield-off': 'shield-off',
  slash: 'blocked',
  sliders: 'sliders',
  smile: 'smile',
  square: 'square',
  star: 'star',
  sun: 'sun',
  thermometer: 'thermometer',
  'trash-2': 'trash',
  type: 'type',
  user: 'user',
  wind: 'wind',
  x: 'close',
  'x-circle': 'close-circle',
  palette: 'palette',
};

export const NURI_ORIGINAL_GLYPHS = {
  feather: [
    'arrow-down',
    'arrow-left',
    'arrow-right',
    'arrow-right-circle',
    'arrow-up',
    'chevron-down',
    'chevron-left',
    'chevron-right',
    'chevron-up',
    'corner-down-right',
    'external-link',
    'log-in',
    'log-out',
    'navigation',
    'refresh-cw',
    'trending-up',
  ],
  material: ['chevron-right', 'google', 'repeat', 'swap-horizontal'],
} as const;

export const NURI_MOOD_ICONS = {
  happy: 'smile',
  calm: 'calm',
  excited: 'excited',
  neutral: 'neutral',
  sad: 'sad',
  anxious: 'anxious',
  angry: 'angry',
  tired: 'tired',
} as const satisfies Record<string, NuriIconName>;

export function resolveNuriIcon(
  family: 'material' | 'feather',
  name: string,
): NuriIconName | undefined {
  const names = family === 'material' ? MATERIAL_NAMES : FEATHER_NAMES;
  return Object.prototype.hasOwnProperty.call(names, name)
    ? names[name]
    : undefined;
}
