begin;

create table if not exists public.community_blocked_terms (
  id bigint generated by default as identity primary key,
  term text not null,
  reason text,
  target_type text not null default 'all',
  target_field text not null default 'all',
  match_mode text not null default 'contains',
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'community_blocked_terms_term_not_blank_check'
      and conrelid = 'public.community_blocked_terms'::regclass
  ) then
    alter table public.community_blocked_terms
      add constraint community_blocked_terms_term_not_blank_check
      check (char_length(btrim(term)) > 0);
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'community_blocked_terms_target_type_check'
      and conrelid = 'public.community_blocked_terms'::regclass
  ) then
    alter table public.community_blocked_terms
      add constraint community_blocked_terms_target_type_check
      check (target_type in ('all', 'post', 'comment'));
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'community_blocked_terms_target_field_check'
      and conrelid = 'public.community_blocked_terms'::regclass
  ) then
    alter table public.community_blocked_terms
      add constraint community_blocked_terms_target_field_check
      check (target_field in ('all', 'title', 'content'));
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'community_blocked_terms_match_mode_check'
      and conrelid = 'public.community_blocked_terms'::regclass
  ) then
    alter table public.community_blocked_terms
      add constraint community_blocked_terms_match_mode_check
      check (match_mode in ('exact', 'contains'));
  end if;
end
$$;

create unique index if not exists uq_community_blocked_terms_rule
  on public.community_blocked_terms (
    public.community_normalize_text(term),
    target_type,
    target_field,
    match_mode
  );

create index if not exists idx_community_blocked_terms_active_scope
  on public.community_blocked_terms (is_active, target_type, target_field, match_mode);

drop trigger if exists trg_community_blocked_terms_updated_at on public.community_blocked_terms;
create trigger trg_community_blocked_terms_updated_at
before update on public.community_blocked_terms
for each row execute function public.set_updated_at();

create table if not exists public.community_blocked_term_patterns (
  id bigint generated by default as identity primary key,
  pattern text not null,
  reason text,
  target_type text not null default 'all',
  target_field text not null default 'all',
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'community_blocked_term_patterns_pattern_not_blank_check'
      and conrelid = 'public.community_blocked_term_patterns'::regclass
  ) then
    alter table public.community_blocked_term_patterns
      add constraint community_blocked_term_patterns_pattern_not_blank_check
      check (char_length(btrim(pattern)) > 0);
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'community_blocked_term_patterns_target_type_check'
      and conrelid = 'public.community_blocked_term_patterns'::regclass
  ) then
    alter table public.community_blocked_term_patterns
      add constraint community_blocked_term_patterns_target_type_check
      check (target_type in ('all', 'post', 'comment'));
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'community_blocked_term_patterns_target_field_check'
      and conrelid = 'public.community_blocked_term_patterns'::regclass
  ) then
    alter table public.community_blocked_term_patterns
      add constraint community_blocked_term_patterns_target_field_check
      check (target_field in ('all', 'title', 'content'));
  end if;
end
$$;

create unique index if not exists uq_community_blocked_term_patterns_rule
  on public.community_blocked_term_patterns (pattern, target_type, target_field);

create index if not exists idx_community_blocked_term_patterns_active_scope
  on public.community_blocked_term_patterns (is_active, target_type, target_field);

drop trigger if exists trg_community_blocked_term_patterns_updated_at on public.community_blocked_term_patterns;
create trigger trg_community_blocked_term_patterns_updated_at
before update on public.community_blocked_term_patterns
for each row execute function public.set_updated_at();

alter table public.community_blocked_terms enable row level security;
alter table public.community_blocked_term_patterns enable row level security;

drop policy if exists "community_blocked_terms_select_admin" on public.community_blocked_terms;
create policy "community_blocked_terms_select_admin"
on public.community_blocked_terms
for select
to authenticated
using (public.is_community_admin());

drop policy if exists "community_blocked_term_patterns_select_admin" on public.community_blocked_term_patterns;
create policy "community_blocked_term_patterns_select_admin"
on public.community_blocked_term_patterns
for select
to authenticated
using (public.is_community_admin());

create or replace function public.raise_community_write_error(
  p_app_code text,
  p_message text,
  p_target_type text default null,
  p_target_field text default null,
  p_match_source text default null,
  p_hint text default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  raise exception using
    errcode = 'P0001',
    message = p_message,
    detail = json_build_object(
      'app_code', p_app_code,
      'target_type', p_target_type,
      'target_field', p_target_field,
      'match_source', p_match_source
    )::text,
    hint = p_hint;
end;
$$;

create or replace function public.assert_community_content_policy(
  p_target_type text,
  p_title text default null,
  p_content text default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  raw_title text := btrim(coalesce(p_title, ''));
  raw_content text := btrim(coalesce(p_content, ''));
  normalized_title text := public.community_normalize_text(p_title);
  normalized_content text := public.community_normalize_text(p_content);
  matched_term_id bigint := null;
  matched_pattern_id bigint := null;
  violation_message constant text := '운영 정책상 등록할 수 없는 표현이 포함되어 있어요. 표현을 조금만 수정해 다시 시도해 주세요.';
begin
  if p_target_type not in ('post', 'comment') then
    return;
  end if;

  if p_target_type = 'post' and raw_title <> '' then
    select t.id
    into matched_term_id
    from public.community_blocked_terms t
    where t.is_active = true
      and t.target_type in ('all', p_target_type)
      and t.target_field in ('all', 'title')
      and (
        (
          t.match_mode = 'exact'
          and (
            btrim(t.term) = raw_title
            or public.community_normalize_text(t.term) = normalized_title
          )
        )
        or (
          t.match_mode = 'contains'
          and (
            position(btrim(t.term) in raw_title) > 0
            or position(public.community_normalize_text(t.term) in normalized_title) > 0
          )
        )
      )
    order by
      case when t.target_type = 'all' then 1 else 0 end,
      case when t.target_field = 'all' then 1 else 0 end,
      t.id
    limit 1;

    if matched_term_id is not null then
      perform public.raise_community_write_error(
        'community_content_policy_violation',
        violation_message,
        p_target_type,
        'title',
        'term',
        '표현을 조금만 수정한 뒤 다시 시도해 주세요.'
      );
    end if;

    select p.id
    into matched_pattern_id
    from public.community_blocked_term_patterns p
    where p.is_active = true
      and p.target_type in ('all', p_target_type)
      and p.target_field in ('all', 'title')
      and (raw_title ~* p.pattern or normalized_title ~* p.pattern)
    order by
      case when p.target_type = 'all' then 1 else 0 end,
      case when p.target_field = 'all' then 1 else 0 end,
      p.id
    limit 1;

    if matched_pattern_id is not null then
      perform public.raise_community_write_error(
        'community_content_policy_violation',
        violation_message,
        p_target_type,
        'title',
        'pattern',
        '표현을 조금만 수정한 뒤 다시 시도해 주세요.'
      );
    end if;
  end if;

  if raw_content <> '' then
    select t.id
    into matched_term_id
    from public.community_blocked_terms t
    where t.is_active = true
      and t.target_type in ('all', p_target_type)
      and t.target_field in ('all', 'content')
      and (
        (
          t.match_mode = 'exact'
          and (
            btrim(t.term) = raw_content
            or public.community_normalize_text(t.term) = normalized_content
          )
        )
        or (
          t.match_mode = 'contains'
          and (
            position(btrim(t.term) in raw_content) > 0
            or position(public.community_normalize_text(t.term) in normalized_content) > 0
          )
        )
      )
    order by
      case when t.target_type = 'all' then 1 else 0 end,
      case when t.target_field = 'all' then 1 else 0 end,
      t.id
    limit 1;

    if matched_term_id is not null then
      perform public.raise_community_write_error(
        'community_content_policy_violation',
        violation_message,
        p_target_type,
        'content',
        'term',
        '표현을 조금만 수정한 뒤 다시 시도해 주세요.'
      );
    end if;

    select p.id
    into matched_pattern_id
    from public.community_blocked_term_patterns p
    where p.is_active = true
      and p.target_type in ('all', p_target_type)
      and p.target_field in ('all', 'content')
      and (raw_content ~* p.pattern or normalized_content ~* p.pattern)
    order by
      case when p.target_type = 'all' then 1 else 0 end,
      case when p.target_field = 'all' then 1 else 0 end,
      p.id
    limit 1;

    if matched_pattern_id is not null then
      perform public.raise_community_write_error(
        'community_content_policy_violation',
        violation_message,
        p_target_type,
        'content',
        'pattern',
        '표현을 조금만 수정한 뒤 다시 시도해 주세요.'
      );
    end if;
  end if;
end;
$$;

create or replace function public.guard_community_post_insert()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  actor_id uuid := auth.uid();
  recent_5m_count integer := 0;
  recent_1h_count integer := 0;
  payload_hash text := '';
begin
  new.title := btrim(new.title);
  new.content := btrim(new.content);
  new.status := coalesce(nullif(btrim(coalesce(new.status, '')), ''), 'active');
  new.visibility := coalesce(new.visibility, 'public');

  perform public.assert_community_actor_is_active();

  if actor_id is null or new.user_id is distinct from actor_id then
    perform public.raise_community_write_error(
      'community_post_write_forbidden',
      '본인 계정으로만 게시글을 작성할 수 있어요.',
      'post'
    );
  end if;

  payload_hash := md5(
    public.community_normalize_text(new.title) || '|' || public.community_normalize_text(new.content)
  );

  select count(*)
  into recent_5m_count
  from public.posts p
  where p.user_id = actor_id
    and p.created_at >= timezone('utc', now()) - interval '5 minutes';

  select count(*)
  into recent_1h_count
  from public.posts p
  where p.user_id = actor_id
    and p.created_at >= timezone('utc', now()) - interval '1 hour';

  if recent_5m_count >= 3 or recent_1h_count >= 10 then
    perform public.raise_community_write_error(
      'community_post_rate_limited',
      '게시글은 5분에 3개, 1시간에 10개까지 작성할 수 있어요. 잠시 후 다시 시도해 주세요.',
      'post'
    );
  end if;

  if exists (
    select 1
    from public.posts p
    where p.user_id = actor_id
      and p.created_at >= timezone('utc', now()) - interval '30 seconds'
      and md5(
        public.community_normalize_text(p.title) || '|' || public.community_normalize_text(p.content)
      ) = payload_hash
  ) then
    perform public.raise_community_write_error(
      'community_post_duplicate_recent',
      '같은 제목과 본문은 30초 안에 다시 등록할 수 없어요.',
      'post'
    );
  end if;

  perform public.assert_community_content_policy('post', new.title, new.content);
  return new;
end;
$$;

drop trigger if exists trg_guard_community_post_insert on public.posts;
create trigger trg_guard_community_post_insert
before insert on public.posts
for each row execute function public.guard_community_post_insert();

create or replace function public.guard_community_post_update()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  actor_id uuid := auth.uid();
begin
  new.title := btrim(new.title);
  new.content := btrim(new.content);

  if new.title is not distinct from old.title
     and new.content is not distinct from old.content then
    return new;
  end if;

  perform public.assert_community_actor_is_active();

  if not public.is_community_admin()
     and (actor_id is null or old.user_id is distinct from actor_id) then
    perform public.raise_community_write_error(
      'community_post_write_forbidden',
      '본인 계정으로만 게시글을 수정할 수 있어요.',
      'post'
    );
  end if;

  perform public.assert_community_content_policy('post', new.title, new.content);
  return new;
end;
$$;

drop trigger if exists trg_guard_community_post_update on public.posts;
create trigger trg_guard_community_post_update
before update of title, content on public.posts
for each row execute function public.guard_community_post_update();

create or replace function public.guard_community_comment_insert()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  actor_id uuid := auth.uid();
  recent_1m_count integer := 0;
  recent_10m_count integer := 0;
  payload_hash text := '';
begin
  new.content := btrim(new.content);
  new.status := coalesce(nullif(btrim(coalesce(new.status, '')), ''), 'active');

  perform public.assert_community_actor_is_active();

  if actor_id is null or new.user_id is distinct from actor_id then
    perform public.raise_community_write_error(
      'community_comment_write_forbidden',
      '본인 계정으로만 댓글을 작성할 수 있어요.',
      'comment'
    );
  end if;

  payload_hash := md5(public.community_normalize_text(new.content));

  select count(*)
  into recent_1m_count
  from public.comments c
  where c.user_id = actor_id
    and c.created_at >= timezone('utc', now()) - interval '1 minute';

  select count(*)
  into recent_10m_count
  from public.comments c
  where c.user_id = actor_id
    and c.created_at >= timezone('utc', now()) - interval '10 minutes';

  if recent_1m_count >= 5 or recent_10m_count >= 20 then
    perform public.raise_community_write_error(
      'community_comment_rate_limited',
      '댓글은 1분에 5개, 10분에 20개까지 작성할 수 있어요. 잠시 후 다시 시도해 주세요.',
      'comment'
    );
  end if;

  if exists (
    select 1
    from public.comments c
    where c.user_id = actor_id
      and c.post_id = new.post_id
      and c.created_at >= timezone('utc', now()) - interval '30 seconds'
      and md5(public.community_normalize_text(c.content)) = payload_hash
  ) then
    perform public.raise_community_write_error(
      'community_comment_duplicate_recent',
      '같은 게시글에는 같은 댓글을 30초 안에 다시 등록할 수 없어요.',
      'comment'
    );
  end if;

  perform public.assert_community_content_policy('comment', null, new.content);
  return new;
end;
$$;

drop trigger if exists trg_guard_community_comment_insert on public.comments;
create trigger trg_guard_community_comment_insert
before insert on public.comments
for each row execute function public.guard_community_comment_insert();

create or replace function public.guard_community_comment_update()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  actor_id uuid := auth.uid();
begin
  new.content := btrim(new.content);

  if new.content is not distinct from old.content then
    return new;
  end if;

  perform public.assert_community_actor_is_active();

  if not public.is_community_admin()
     and (actor_id is null or old.user_id is distinct from actor_id) then
    perform public.raise_community_write_error(
      'community_comment_write_forbidden',
      '본인 계정으로만 댓글을 수정할 수 있어요.',
      'comment'
    );
  end if;

  perform public.assert_community_content_policy('comment', null, new.content);
  return new;
end;
$$;

drop trigger if exists trg_guard_community_comment_update on public.comments;
create trigger trg_guard_community_comment_update
before update of content on public.comments
for each row execute function public.guard_community_comment_update();

commit;
